### ISSUE TITLE
SFCB server returns XML error from OpenEnumerateInstances

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1013]
When working with a production SMI-S envrionment, it refuses the instance enumerate command with the following error:

pywbemcli> instance enumerate cim_computer
Error: CIMError: 1 (CIM_ERR_FAILED): invalid imethodcall XML

Setting the --use-pull no to turn off pull returns good instances.

The server was identified as SFCB.

**Comment by andy-maier** [comment]
Pywbem PR https://github.com/pywbem/pywbem/pull/2738 fixes that. I don't think that further changes are needed in pywbemtools. Please test again with the pywbem fix.

**Comment by andy-maier** [comment]
Corrected server name to SFCB.

**Comment by andy-maier** [comment]
Karl successfully tested PR pywbem/pywbem#2738 with SFCB. No further changes needed on the pywbemcli side.
