### ISSUE TITLE
Strange results when -o table used with EnumerateInstances on SFCB server

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1016]
We are getting different results from a pywbemcli request "instance enumerate" when the -o table form is used than when the default output format is used.

TODO: Add the detail data.

**Comment by andy-maier** [comment]
Corrected server name to SFCB.

**Comment by andy-maier** [comment]
Is this a duplicate of #1014 or a separate issue?

**Comment by andy-maier** [comment]
We discussed this one. karl says it is in fact a duplicate of #1014. Closing it as a duplicate.
