### ISSUE TITLE
logging cannot be enabled in the interactive mode without selecting the server

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1023]
Logging is defined and enabled as part of the PwybemServer.connect method, including the confirmation of the validity of the parameters but log is not part of the parameters of the PywbemServer class.   Therefore, it can be only established when a pywbemserver is createed with the pywbemserver.connect() method.  There are two issues here 1. The validation of the logging parameters is combined with the establishment of logging.   The connect is only called when the wbem_server property is called and only if it does not exist.

**Comment by andy-maier** [comment]
The pywbemcli logging feature is (only) for logging the interactions with a WBEM server.
Why is tying it to a server a problem?

**Comment by andy-maier** [comment]
We discussed this and the issue is that it fails when trying to turn on logging in the interactive session. Needs to be fixed.

**Comment by andy-maier** [comment]
After reviewing PR #1029 it seems to me that the change is too large to be rolled back to 0.9 as a fix.
