### ISSUE TITLE
Use of geneal options in interactive command not consistent.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1033]
This issue started off of pywbem issue #2750, the deepcopy exception.  It lead us to propose a review of the use of the
cmd line parameters in interactive commands. For the moment we are carrying that discussion in the pywbem issue.  I propose that we document any proposed changes here after the discussion

**Comment by andy-maier** [comment]
The details are in these issues:
* https://github.com/pywbem/pywbemtools/issues/1034
* https://github.com/pywbem/pywbem/issues/2750
