### ISSUE TITLE
pywbemcli restricts parameters on cmd line when the --name is used

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1034]
Pywbemcli restricts the general options that are part of the the connection configuration when the --name parameter is part of the cmd line.  I.e. it does not allow getting a connection definition from a connections file and modifying the parameters of that connection as part of the startup process.

The restricted parameters include:
* default_namespace
* timeout
* verify
* user
* certfile
* keyfile
* ca_certs
* server
* mock_server

There are a number of use cases where the capability to a)get a named connection definition, b) modify that connection definition, and c) do something with that connection definition in a single cmd line call are useful including things like testing variations of a definition that today require either modifying the named connection definition or using the interactive mode.

thus for example:

   pywbmecli -n pegasus --timeout 90 class enumerate

should be allowed

This is too restrictive.  We propose to remove these restrictions so all but conflicting parameters can be defined on the command line  along with the --name option.

We propose that the restrictions be limited to:
* cannot have both server and mock_server
* Warning if genera options that do not apply to mock_server exist with when --mockserver option exists.

**Comment by andy-maier** [comment]
A more detailed writeup of the desired behavior is in https://github.com/pywbem/pywbem/issues/2750.

**Comment by KSchopmeyer** [comment]
# Table of general parameters and their requirements, usage in pywbemcli

There are two possible contexts for a parameter:

1. connection: The parameter sets a parameter of the connection and requires
   that the connection be reset to enable a changed parameter
3. cmd: The parameter modifies behavior of the command itself and does not
   impact the connection.

NOTE: There is a third possibility, in that the parameter is part of the connection
but could be set into or used by the connection without requiring that the connection be reset.

The column type defines whether the parameter applies to the WBEMConnection (real),
FakedWBEMConnection (mock) or both types.


|Context        |type | general option name | Description    | Actions               | Note |
|---------------|-----|---------------------|----------------|-----------------------|------|
| connection    |both | name                | connection name| Not implemented       |  4 ,5  |
| connection    |real | server              | url            | change url,           |      |
|               |     |                     |                | reset server. see note|      |
| connection    |real | default-namespace   |                |                       |  3   |
| connection    |real | user                | user name      |                       |  4   |
| connection    |real | password            | user password  |                       |  5   |
| connection    |both | timeout             | client timeout |                       |  1   |
| connection    |both | use-pull            |                |                       |  4   |
| connection    |both | max-pull-count      | integer        |                       |  2   |
| connection    |real | verify              | ssl verify flag|                       |  4   |
| connection    |real | certfile            |                |                       |  4   |
| connection    |real | keyfile             |                |                       |  4   |
| connection    |real | ca-certs            |                |                       |  4   |
| connection    |mock | mock-server         | scripts/mof    |                       |  4   |
| cmd           |both| verbose              |                | set in each           |      |
|               |     |                     |                | context               |      |
| cmd           |both| timestats            | Enable/disable | Set for each          |      |
|               |     |                     | statistics     | command when connected|      |
| cmd           |both| format               |                | set in each context   |      |
|               |     |                     |                | context obj, available|      |
|               |     |                     |                | for each cmd          |      |
| cmd           |both| log                  | config/enable  |Changes server         |      |
|               |     |                     | logging        | but now set for       |      |
|               |     |                     |                | eacn interactive cmd  |      |
| cmd           |both| pdb                  | enable brkpnt  | set at startup and    |      |
|               |     |                     |                | not changed           |      |
| TODO              |     | connections-file    |                |                       |      |



Notes:

1. The WBEMConnection timeout is only settable at the level of the connection  __init__ but could be
   settable at any time the connection exists because the value is passed to the requests code each time
   a request is issued. While this applies to the connection and is persisted with the connection
   definition, thee usage could be considered either connection or session.

2. max-pull-count is maintained in the context_obj and each instance enumerate, assoc, reference, etc.
   that needs it gets it from the contextobj. Therefore in the interactive mode setting this value through
   the general options sets the max_pull-count for that command and the original value is restored for the
   next command.

3. default_namespace is settable in WBEMConnection and therefore could be considered modifiable for
   each command.  Thus, an interactive command could set it and that would be the default for that
   command.  However, since each command also has its own namespace parameter this is a duplication
   of effort.

4. This parameter can only be set into WBEMConnection on init of the connection. It is also only used
   on connection.  Modifying this in an interactive command causes the connection to be closed and
   reopened.  In the current implementation, generally this parameter causes the connection to be closed
   so the connect() with the command execution inserts the modified parameter into the connection.
   Also, the succeeding command resets the parameter back to the cmd line definition and again closes
   the connection.

5. The --name is currently not considered in the set of general options that can be used to modify a command in
    the interactive mode.  Note that the --name general option when used in interactive mode brings other questions.  
   Does it    mean    that the name server should be loaded or that the --name should override the existing name in the
   connection definition.  To be consistent it must cause the connection defined by the --name to be loaded
   same as the use at any other time. 

# Initialization parameters for WBEMConnection and FakedWBEMConnection

WBEMConnection _init paramsurl, creds=None, default_namespace=None, x509=None,
 ca_certs=None, no_verification=False, timeout=None, use_pull_operations=False, stats_enabled=False, proxies=None

# WBEMConnection properties have the following setters:

1. default_namespace
2. operation_recorder_enabled
3. stats_enabled
4. debug

FakedWBEMConnection(default_namespace='root/cimv2', use_pull_operations=False, stats_enabled=False, timeout=None,
response_delay=None, disable_pull_operations=None, url=None

# Known issues:

max-pull-count is considered cmd level but could be session. Max pull-count is only
used at the command level. It is carried in the context and each command that requires it gets
it from the context.  Therefore it is used for the current command if that command is an
instance enumerate, associators, etc.

# Other open questions on pywbemcli

1. Restriction of modification of parameters when --name is used on the command line.  We agreed to remove the restriction and issue pywbemcli #1047 has been created defining this change

**Comment by KSchopmeyer** [comment]
From your table above, I created this comment.

These tables describe the desired behavior for different override situations (meant to be a proposal), and lists the required changes to the existing implementation (incomplete).

Next steps:
* Agree on desired behavior
* Determine changes to existing implementation

**Options with connection context:**

Kinds of overrides:

* "conn -> opt" - If the --name option is specified on a command, what should happen when the option in question is specified on the same command. This applies to both command line commands and interactive session commands.
  **QUESTION/KS:** I do not understand this one.  Can we get an example.
  **ANSWER/AM:** Examples for the table row with the `timeout` option:
  `$ pywbemcli --name conn1 --timeout 30 {some-command}` for the command line level
  `> --name conn1 --timeout 30 {some-command}` for the interactive level

* "cmd -> int" - If there is a connection inherited from the command line to an interactive session, what should happen when the option in question is specified on an interactive command in that session. This applies regardless of how the connection at the command line level was crafted.

The 'desired' columns describe the desired behavior:
* 'update PS' means to update the currently used PywbemServer object from the option.
* 'reset+update PS' means to reset the currently used PywbemServer object to default values and then to update it from the option. This is processed as the first option.
* 'replace PS' means to update the currently used PywbemServer object from the new connection, replacing all connection attributes.

The 'changes' columns describe the necessary changes to the existing implementation, in order to have the desired behavior.

| type | general option name | desired conn -> opt | desired cmd -> int | changes conn -> opt | changes cmd -> int |
|:---- |:------------------- |:------------------- |:------------------ |:------------------- |:------------------ |
| both | name                | N/A                 | replace PS         |                     |                    |
| mock | mock-server         | reject              | reset+update PS    |                     |                    |
| real | server              | reject              | reset+update PS    |                     |                    |
| real | default-namespace   | update PS           | update PS          | remove rejection    |                    |
| real | user                | update PS           | update PS          | remove rejection    |                    |
| real | password            | update PS           | update PS          |                     |                    |
| real | verify              | update PS           | update PS          | remove rejection    |                    |
| real | certfile            | update PS           | update PS          | remove rejection    |                    |
| real | keyfile             | update PS           | update PS          | remove rejection    |                    |
| real | ca-certs            | update PS           | update PS          | remove rejection    |                    |
| both | timeout             | update PS           | update PS          | remove rejection    |                    |
| both | use-pull            | update PS           | update PS          |                     |                    |
| both | pull-max-cnt        | update PS           | update PS          | add to PS           |                    |

**Options with cmd context:**

The 'desired' column describes the desired behavior:
* 'inherit+update' means to inherit the command line value of the option into the interactive session, and then to override it from the option on the interactive command, if specified.

The 'changes' column describes the necessary changes to the existing implementation, in order to have the desired behavior.

| type | general option name | desired            | changes            |
|:---- |:------------------- |:------------------ |:------------------ |
| both | verbose             | inherit+update     |                    |
| both | timestats           | inherit+update     |                    |
| both | format              | inherit+update     |                    |
| both | log                 | inherit+update     |                    |
| both | pdb                 | inherit+update     |                    |

**Other changes:**

* Reject type-specific connection options when the connection is not of that type
