### ISSUE TITLE
We do not allow use of the --connections-file general option in interactive mode

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1037]
In the original code we do not allow modification of the connections file in interactive mode.  That was an early check since the interactive mode was already complex.

**PROPOSAL:**This limitation is not necessary and that it should be just like other changes executed in the interactive mode. Applies to the current command and then the original connection file parameter is restored.

The only issue with this that I can see so far is user confusion because of duplicate connection names if a save occurs to a temporarly assigned connection file.

**Comment by KSchopmeyer** [comment]
We agree to remove this restriction for this release

**Comment by andy-maier** [comment]
We agreed to move this one out to 1.1.0
