### ISSUE TITLE
Warning message not using python warning construct

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1041]
Pywbemcli outputs warnings about invalid formatting of the Version qualifier value (too few or too many items  (ex 2.4.1.1 or 2.4) or an item that is not an integer)in processing instances of this qualifier. However we do not use the warnings logic but just output a click.echo.  Note that, at the same time, the MOF compiler completely ignores these issues.

If these are issues as warnings they should be using the warning class with all of its capabilities.

The question would be, given that this is a warming about an issue with data in a CIM class which of the warning categories would make sense  (RuntimeWarning, SyntaxWarning , UserWarning ,  ResourceWarning)? Or should we just drop the warning aoll together and just fix the errors so we can conduct our tests.)?

**Comment by andy-maier** [comment]
The only place in the code that checks the format of the Version qualifier that I found so far, is in `_cmd_class.py`:
```
def parse_version_str(version_str):
    """..."""
    try:
        version_tuple = [int(x) for x in version_str.split('.')]
    except ValueError:
        raise click.ClickException('--since option value invalid. '
                                   'Must contain 3 integer elements: '
                                   'int.int.int". {} received'.
                                   format(version_str))
    if len(version_tuple) != 3:
        raise click.ClickException('Version value must contain 3 integer '
                                   'elements (int.int.int). '
                                   '{} received'.format(version_str))
    return version_tuple
```

The only command that invokes this function (indirectly) is `class enumerate` and the exception raised in the function shown above is not handled anywhere in between, so it results in a command failure. It does not result in a warning from what I could see in the code.

Do you have an example command that shows this check as a warning, i.e. where the rest of the command continues to execute?

**Comment by KSchopmeyer** [comment]
No. That was the one place that the call to the warning message occurs.   This appears as the warning message in pytest.

**Comment by KSchopmeyer** [comment]
The issue and pr #1069 were, in fact, linked correctly.  For some reason the issue was not closed.

I am closing this one as fixed.
