### ISSUE TITLE
Weird formatting of SourceNamespaces in subscription list-filters

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#1053]
In the table format on subscription list-filters has a strange format of SourceNamespaces. It puts a comma after each letter of a namespace.

**Comment by KSchopmeyer** [comment]
This issue occurred in a test of an earlier commit of this branch.  We confirmed that it does not occur in the current working branch at least on linux.  Will test with the latest version of the branch on windows.

**Comment by FarmerMike252** [comment]
Well, the formatting has changed, but it is still not right on Windows. Now the name of the namespace displays vertically. 

pywbemcli> subscription list-filters
Indication Filters: submgr-id=defaultpywbemcliSubMgr, svr-id=http://FakedUrl:5988 type=all
+-------------+-------------------------------------------+-------------------------------+--------------------------------------------------------+------------+--------------+----------------+
| Ownership   | identity                                  | Name                          | Query                                                  | Query      | Source       |   Subscription |
|             |                                           |                               |                                                        | Language   | Namespaces   |          Count |
|-------------+-------------------------------------------+-------------------------------+--------------------------------------------------------+------------+--------------+----------------|
| permanent   | System Creation                           | System Creation               | SELECT * FROM                                          | DMTF:CQL   | i            |              0 |
|             |                                           |                               | CIM_InstCreation WHERE                                 |            | n            |                |
|             |                                           |                               | SourceInstance ISA                                     |            | t            |                |
|             |                                           |                               | CIM_ComputerSystem                                     |            | e            |                |
|             |                                           |                               |                                                        |            | r            |                |
|             |                                           |                               |                                                        |            | o            |                |
|             |                                           |                               |                                                        |            | p            |                |

**Comment by FarmerMike252** [comment]
I am closing this as "user error."
