### ISSUE TITLE
Do not enforce the rule that instances of Abstract cannot be created

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#1054]
Most profile designers were not aware that abstract classes are not supposed to be created. For example, the SNIA Server Profile requires a CIM_System. My mock blew  up trying  to load my Array Mock with the following error:

subscription list-filters
-Loading classes into the Mock Repository
-Loading instances into the Mock Repository
/Mock script ArrayMockLoad.py failed: CIM repository error:MockSNIA_ArrayInstances.mof:11:0 Cannot compile instance of 'CIM_System' because the CIM repository returned an error for CreateInstance
   // CIM_System
1 (CIM_ERR_FAILED): CreateInstance failed. Cannot instantiate abstract class 'CIM_System' in Namespace 'interop'.
Aborted!

**Comment by FarmerMike252** [comment]
I realize this  may be technically correct from a CIM spec point of view (although I have not researched this).  But clearly SNIA did not realize this and SMI-S clearly states that a CIM_System is required. I suspect there may be problems with DMTF profiles as well.

**Comment by KSchopmeyer** [comment]
Since this is a solution for existing code, the idea of trying to go back and clean up the models does not work.

The test itself is in the pywbem mof compiler and, as such is an easy change.

Rather than making this conditional, I propose that we simply issue a warning message (Invalid MOF or something like that for this issue rather than an exception.

**Comment by andy-maier** [comment]
We decided to go ahead with this one and change the error in the MOF compiler to a warning message.

**Comment by andy-maier** [comment]
We created pywbem issue https://github.com/pywbem/pywbem/issues/2825 to address this.
