### ISSUE TITLE
Extend Subscription commands to keep SubscriptionManager in interactive mode

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1067]
Retain SubscriptionManager object between commands in interactive mode.

This may be simple since the SubscriptionManager is capable of handling multiple wbem server within a single instance by adding and removing server_id entities.

The simplest is simply to change the code to:

a. Create a variable to hold the SubscriptionManager object in the context.
b. For each command use the existing context if it exists and add a new server if the server for this command does not exist in the context.
c. Consider possibly removing other server_ids when a new one is added but that is probably excessive at least for now.

ISSUES:

Since we will be keeping the subscription manager status between commands, there is one issue, keeping the local list of all  subscriptions up-to-date with the server.

**Comment by andy-maier** [comment]
For some reason, the issue and the PR cannot be linked. This issue was fixed in PR #1095
