### ISSUE TITLE
Add limits so -o table instance enumerate <...> is more logical

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1131]
The table outputformat of the instance enumerate, get, etc. has one real problem in that it creates a table with a column for each property displayed but sets no limits on the number of properties so that a class with many properties would produce an unreadable table.

Thus, for example, consider the following instance:

```
instance of PG_SoftwareIdentity {
   Caption = NULL;
   Description = NULL;
   ElementName = NULL;
   InstallDate = NULL;
   Name = "benchmarkProvider (C++Default)";
   OperationalStatus = NULL;
   StatusDescriptions = NULL;
   Status = NULL;
   HealthState = NULL;
   CommunicationStatus = NULL;
   DetailedStatus = NULL;
   OperatingStatus = NULL;
   PrimaryStatus = NULL;
   InstanceID = "benchmarkProviderModule+benchmarkProvider";
   MajorVersion = NULL;
   MinorVersion = NULL;
   RevisionNumber = NULL;
   BuildNumber = NULL;
   LargeBuildNumber = NULL;
   IsLargeBuildNumber = false;
   VersionString = "2.2.0";
   TargetOperatingSystems = NULL;
   Manufacturer = "OpenPegasus";
   Languages = NULL;
   Classifications = { 5 };
   ClassificationDescriptions = NULL;
   SerialNumber = NULL;
   TargetTypes = NULL;
   IdentityInfoValue = NULL;
   IdentityInfoType = NULL;
   ReleaseDate = NULL;
   IsEntity = false;
   ExtendedResourceType = NULL;
   OtherExtendedResourceTypeDescription = NULL;
   MinExtendedResourceTypeMajorVersion = NULL;
   MinExtendedResourceTypeMinorVersion = NULL;
   MinExtendedResourceTypeRevisionNumber = NULL;
   MinExtendedResourceTypeBuildNumber = NULL;
   TargetOSTypes = NULL;
};
```

40 properties simply cannot be displayed in a table output.  We just created a pr to fix an issue where this actually caused an exception because the resulting width of each column was so small but that was a band-aid, not a fix for the displayablity issue.

There are a couple of possible solutions including:

1. Eliminate properties that have NULL value in all instances for table output.  Note that in the above example almost half of the properties have NULL value. Doing that as a command option appears illogical since it is only really True for the table output, not for MOF. 
2. Set a maximum number of properties for table output and if the user requests more (or all properties if --pl not specified exceeds the limit) generate an exception that gives them more information.  Thus, for example, 12 properties would be a logical (maybe even excessive) limit since each we normally have about 120 character width to work with for table output and the the cell boundaries take about 3 characters per column so that for 12 columns, the columns would be folded to less than 8 characters of data per column.  Note: we do fold the property names to match the computed max column width.
3. Make the width greater than the terminal width. so at least the user sees a table if they widen the terminal.

We agree that we should implement optiosn 1 and 3. 

We will do option --all for table view to show columns with properties that have no value.

**Comment by andy-maier** [comment]
**DISCUSSION**: PR #1136 addresses NULL properties. Does this completely address this issue?
