### ISSUE TITLE
Directions and Priorities for pywbemtools 1.1.0

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1146]
### For information:
* [Open issues targeting 1.1.0](https://github.com/pywbem/pywbemtools/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.1.0)
* [Open issues not targeting any milestone](https://github.com/pywbem/pywbemtools/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+no%3Amilestone+-label%3A%22type%3A+DMTF+issue%22)

### Ongoing items in each release:
* Resolve [open bugs](https://github.com/pywbem/pywbemtools/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A%20bug%22)
* Improve test coverage ( coverage at release of version 1.0.0 was 92%)
* Expand use of documentation index
* Work down TODOs
* Review current experimental functionality for finalization:
* Consider dropping deprecated functionality:
  - ‘server namespaces’ and ‘server interop’ commands, deprecated in 0.9.0.

### High level topics and themes for the release:

- All of the items tagged for this release (See link above for list)
- Modify to use click version 8 including:
  - test with all versions of python that allow this click version and with click 7 for python versions that do not allow click 8.  (see issue #1149)
  - Determine if we can use click-7 and python 2.7/3.5 (really 2.7) with minimal changes to pywbemtools. (Issue # 1149)
  - Test the use of tab-complete, at least for commands (i.e. match what is in pywbemcli 1.0
  - Document tab-complete setup and usage in the pywbemtools documentation. (See issue #1158)
 - Consider adding at least some variable tab completion support (ex. --name global option)

 - Extend pywbemcli to allow some form of short form of commands where we do not have to type in the full command name  for each use.  Thus, something where something like "sub af"  would be the same as "subscription add-filter". We consider this low priority.
 
 - Drop python 2.7 - **DISCUSSION**.  See the same issue discussed above with respect to click8.
 
 - Define a mechanism where we could actually group options in addition to the current extension to do mutually exclusive options.  Note that while there is a click contrib that does this: https://github.com/click-contrib/click-option-grouo this contribution is limited to python 3.6 and above and specifically has functionality that is only available in python 3.6 (ex. pathlib)
 -

**Comment by FarmerMike252** [comment]
My work plan on SMI-S mocks is:
1. Fix the WBEM Server mock (it is currently broken)
2. Convert the mocks from one namespace to 2 namespaces
3. Add a Fabric Mock
Given this plan, the issues that I would like to see addressed are:
Convenient function for mock scripts to create interop namespace
- I am getting 'no interop namespace' errors on some (the WBEM server mock), but not other mocks (e.g., Array mock).
Show namespace on display of classes and instances
- I won't be going to multiple namespaces in my mocks without a solution for this.
Allow multiple namespaces where ever the -n option exists
- I won't be going to multiple namespaces in my mocks without a solution for this.
Need to wrap column values in the Table format of subscription list-filters
- This would be a nice to have. I currently use mof format or property lists to get around the problem.
