### ISSUE TITLE
Prompt_toolkit incompatibility.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#117]
The prompt-toolkint v 2 was released in June 2018. However it is incompatible with how we are building our repl_prompt and results in an erro from the toolkit upon the

    click_repl.repl(ctx, prompt_kwargs=prompt_kwargs)

call.

It causes an exception whenever pywbemcli is called with no group so that the repl is inisiated.

For now I propose that we lock ourselves to the 1.x version of the toolkint

**Comment by KSchopmeyer** [comment]
This has been documented in the issues for click_repl. 

https://github.com/click-contrib/click-repl/issues/43

**Comment by andy-maier** [comment]
Addressed with PR #143.
