### ISSUE TITLE
sphinx issues.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1218]
Marked priority becasue first problem (bullet lists) makes document very hard to read.  Did not set rollback needed because as soon as we release 1.1.0, it will become stable doc so issue disappears.

**1. pywbemtools Documentation does not  display bullet lists bullets so difficult it is to visualize lists:**

Example of issue:
Source code for the lines:

```
    This package contains WBEM command line tools:
  
    * pywbemcli - a WBEM client CLI for interacting with WBEM servers
    * pywbemlistener - a tool that runs and manages WBEM listeners

```

The display when the docs are built locally  shows the bullets for the two items in the list. However the bullet lists on ReadTheDocs look like the one here:

===============

![image](https://user-images.githubusercontent.com/2340817/196233657-5c9ea39e-5603-43fc-8ade-e44bf0427ec1.png)

===============

The HTML produces by sphinx is as follows:

    <p>This package contains WBEM command line tools:</p>
    <ul class="simple">
    <li><p>pywbemcli - a WBEM client CLI for interacting with WBEM servers</p></li>
    <li><p>pywbemlistener - a tool that runs and manages WBEM listeners</p></li>
    </ul>

with no bullet leading each of the bullet list  lines

**NOTE:** This really shows up in the changes section that is completely structured as bullet lists where the lists just show up as paragraphs

Rendering in local doc build

![image](https://user-images.githubusercontent.com/2340817/196463300-b32914d2-28c6-4a0b-b3fa-eb6d374e72ae.png)

This is an issue in pywbemtools documentation  but NOT pywwbem documentation which shows the bullet lists correctly in the doc on ReadTheDocs

This issue has occurred before in other projects and has in at least one case been tied to docutils:

     See issue https://github.com/readthedocs/sphinx_rtd_theme/issues/1115 which recommends limiting docutils to version <=0.16.0

However, in our case, we are using docutils 1.17.1 on both pywbem and pywbemtools.

NOTES:
* Both latest and stable in pywbem doc OK.  
* Both latest and stable doc  pywbemtoolshave show the error
*  Docutils versions same (0.17.1) pywbemtools and pywbem
* sphinx-rtd-theme same  (1.0.0) pywbemtools and pywbem
* Several differences in rtd-requirements.txt (see next comment) 
* This can only be tested if ReadTheDocs executes the build (i.e. merge into master) or release

Assumption right now. It is some difference in our rtd-requirements or in the configuration of ReadTheDocs itself since there are a bunch of config variables in setting that up.

**2. Edit in Github button in pywbemtools doc upper right of output page**
The local build of the pywbemtools docs includes in the upper right hand corner of the page  "View source on github" as a button whereas the docs in reathedocs the test is "Edit on Github.  This occurs with both pywbem and pywbemtools.  

There are references to use of html_theme_options variable and the following from ReadTheDocs https://docs.readthedocs.io/en/latest/guides/remove-edit-buttons.html#

**Comment by KSchopmeyer** [comment]
rtd-requirements.txt differences

```

pywbem(master)$ diff rtd-requirements.txt ../../pycli39/pywbemtools/rtd-requirements.txt -y
# Requirements for building pywbem docs with Sphinx at readth |	# Requirements for building with Sphinx at readthedocs.org
#								#
# The order of packages is significant, because pip processes <
# of appearance.					      <
							      <
-r requirements.txt					      <
							      <
# Minimum set of packages for Sphinx processing		      <
# Keep in sync with dev-requirements.txt		      <

							      >	six>=1.14.0
							      >	ply>=3.10
							      >	PyYAML>=3.13
							      >	# M2Crypto>=0.30.1  # we cannot install M2Crypto because RTD 
Sphinx>=1.7.6,<2.0.0; python_version == '2.7'			Sphinx>=1.7.6,<2.0.0; python_version == '2.7'
Sphinx>=3.5.4,<4.0.0; python_version == '3.5'		      |	Sphinx>=3.5.4,!=4.0.0; python_version >= '3.5'
Sphinx>=3.5.4; python_version >= '3.6' and python_version <=  <
Sphinx>=4.2.0; python_version >= '3.10'			      <
docutils>=0.13.1,<0.17; python_version == '2.7'			docutils>=0.13.1,<0.17; python_version == '2.7'
docutils>=0.13.1; python_version >= '3.5'			docutils>=0.13.1; python_version >= '3.5'
sphinx-git>=10.1.1						sphinx-git>=10.1.1
GitPython>=2.1.1					      <
sphinxcontrib-fulltoc>=1.2.0					sphinxcontrib-fulltoc>=1.2.0
sphinxcontrib-websupport>=1.1.2				      <
sphinx-rtd-theme>=0.5.0					      <
autodocsumm>=0.1.13,<0.2.0; python_version == '2.7'	      <
autodocsumm>=0.1.13,<0.2.4; python_version == '3.5'	      <
autodocsumm>=0.2.5; python_version >= '3.6'		      <

**Comment by KSchopmeyer** [comment]
versions used in test
PYWBEM
Sphinx                             1.8.6
sphinx-git                         11.0.0
sphinx-rtd-theme                   1.0.0
sphinxcontrib-fulltoc              1.2.0
sphinxcontrib-websupport           1.1.2

PYWBEMTOOLS
Sphinx                        5.3.0
sphinx-git                    11.0.0
sphinx-rtd-theme              1.0.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-fulltoc         1.2.0
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5

**Comment by andy-maier** [comment]
Item 1 can be solved by indenting the bullets by two:
```
This package contains WBEM command line tools:

  * pywbemcli - a WBEM client CLI for interacting with WBEM servers
  * pywbemlistener - a tool that runs and manages WBEM listeners
```

**Comment by andy-maier** [comment]
Here is one more issue with the docs:

A fresh build on Python 3.9 displays this warning:
```
/Users/maiera/PycharmProjects/pywbem/pywbemtools/docs/pywbemcli/mock_support.rst:110: ERROR: Error in "index" directive:
no content permitted.

.. index:: pair: mock server cache; cache mock server

  Since the mock repository created by mock scripts and MOF files can be cached, pywbemcli
  can also make the decision on pywbemcli with the :ref:`--name general option`
  whether the script is to retrieved from the cache or recreated from the
  named connection definition.  To do this, it needs knowledge of whether
  the files that make up  the script have been modified since the cache
  of the repository was created. To do this the files that are used in
  the script have to be registered with the pywbem provider_dependent_registry.
  using :meth:`~pywbem_mock:provider_dependent_registry.add_dependents`

  Finally, mock scripts can be used to add or update CIM objects in the mock
  CIM repository. This is an alternative to specifying MOF files, and can be
  used for example to parse files defining the CIM objects for entire WBEM
  management profiles.
```

**Comment by andy-maier** [comment]
Some more warnings during Sphinx build:

```
sphinx-build -b html -v -d build_doc/doctrees -c docs -D latex_elements.papersize=a4 docs build_doc/html
Running Sphinx v5.3.0
WARNING: Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
making output directory... done
locale_dir /Users/maiera/PycharmProjects/pywbem/pywbemtools/docs/locales/en/LC_MESSAGES does not exists
loading intersphinx inventory from https://docs.python.org/2/objects.inv...
loading intersphinx inventory from https://docs.python.org/2/objects.inv...
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://pywbem.readthedocs.io/en/stable/objects.inv...
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
WARNING: extlinks: Sphinx-6.0 will require a caption string to contain exactly one '%s' and all other '%' need to be escaped as '%%'.
locale_dir /Users/maiera/PycharmProjects/pywbem/pywbemtools/docs/locales/en/LC_MESSAGES does not exists
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 17 source files that are out of date
updating environment: locale_dir /Users/maiera/PycharmProjects/pywbem/pywbemtools/docs/locales/en/LC_MESSAGES does not exists
[new config] 17 added, 0 changed, 0 removed
reading sources... [  5%] appendix
```

**Comment by andy-maier** [comment]
For the item 2 in the original description: I would just ignore that. We could figure out how RTD builds differently, but do we care?

**Comment by KSchopmeyer** [comment]
The issue concerning warnings from builddoc in one of the comments above are fixed by pr #1219..

**Comment by KSchopmeyer** [comment]
Here are  the  requirements for the various sphinx tools for all the requirements files between pywbem and pywbem doc:

**PYWBEMCLI  search for docutils in *.txt**

minimum-constraints.txt
186:docutils==0.13.1; python_version == '2.7'
187:docutils==0.13.1; python_version >= '3.5' and python_version <= '3.9'
188:docutils==0.14; python_version >= '3.10'

docs/pywbemcli/generaloptions.rst
1386:.. _`reStructuredText`: http://docutils.sourceforge.net/docs/user/rst/quickref.html#tables

docs/_static/basic.css
315:table.docutils {
327:table.docutils td, table.docutils th {

rtd-requirements.txt
10:docutils>=0.13.1,<0.17; python_version == '2.7'
11:docutils>=0.13.1; python_version >= '3.5'

dev-requirements.txt
73:#   types.Union. This also drives docutils>=0.14.
74:# Sphinx pins docutils to <0.18 (some versions even to <0.17) but the package
79:docutils>=0.13.1,<0.17; python_version == '2.7'
80:docutils>=0.13.1; python_version >= '3.5' and python_version <= '3.9'
81:docutils>=0.14; python_version >= '3.10'

**PYWWBEM search for docutils in *.txt**

minimum-constraints.txt
196:docutils==0.13.1; python_version == '2.7'
197:docutils==0.13.1; python_version >= '3.5' and python_version <= '3.9'
198:docutils==0.14; python_version >= '3.10'

docs/changes.rst
371:  docutils 0.18.  (See issue # 2787).

docs/_static/basic.css
315:table.docutils {
327:table.docutils td, table.docutils th {

rtd-requirements.txt
15:docutils>=0.13.1,<0.17; python_version == '2.7'
16:docutils>=0.13.1; python_version >= '3.5'

dev-requirements.txt
49:#   types.Union. This also drives docutils>=0.14.
50:# Sphinx pins docutils to <0.18 (some versions even to <0.17) but the package
57:docutils>=0.13.1,<0.17; python_version == '2.7'
58:docutils>=0.13.1; python_version >= '3.5' and python_version <= '3.9'
59:docutils>=0.14; python_version >= '3.10'

**PYWBEMCLI  search for sphinx in *.txt**

dev-requirements.txt
68:# Sphinx (no imports, invoked via sphinx-build script):
82:sphinx-git>=10.1.1
84:sphinxcontrib-fulltoc>=1.2.0
87:sphinx-rtd-theme>=0.5.0

minimum-constraints.txt
182:# Sphinx (no imports, invoked via sphinx-build script):
189:sphinx-git==10.1.1
191:sphinxcontrib-fulltoc==1.2.0
192:sphinxcontrib-websupport==1.1.2
195:sphinx-rtd-theme==0.5.0
307:sphinxcontrib-applehelp==1.0.0; python_version >= '3.5'
308:sphinxcontrib-devhelp==1.0.0; python_version >= '3.5'
309:sphinxcontrib-htmlhelp==1.0.0; python_version >= '3.5' and python_version <= '3.9'
310:sphinxcontrib-htmlhelp==2.0.0; python_version >= '3.10'
311:sphinxcontrib-jsmath==1.0.0; python_version >= '3.5'
312:sphinxcontrib-qthelp==1.0.0; python_version >= '3.5'
313:sphinxcontrib-serializinghtml==1.1.5; python_version >= '3.5'

rtd-requirements.txt
12:sphinx-git>=10.1.1
13:sphinxcontrib-fulltoc>=1.2.0

**PYWBEM Search for sphinx in *.txt**

dev-requirements.txt
43:# Sphinx (no imports, invoked via sphinx-build script):
60:sphinx-git>=10.1.1
64:sphinxcontrib-fulltoc>=1.2.0
65:sphinxcontrib-websupport>=1.1.2
68:sphinx-rtd-theme>=0.5.0

minimum-constraints.txt
192:# Sphinx (no imports, invoked via sphinx-build script):
199:sphinx-git==10.1.1
201:sphinxcontrib-fulltoc==1.2.0
202:sphinxcontrib-websupport==1.1.2
203:sphinxcontrib-applehelp==1.0.2; python_version >= '3.5'
204:sphinxcontrib-devhelp==1.0.2; python_version >= '3.5'
205:sphinxcontrib-htmlhelp==1.0.3; python_version >= '3.5' and python_version <= '3.9'
206:sphinxcontrib-htmlhelp==2.0.0; python_version >= '3.10'
207:sphinxcontrib-jsmath==1.0.1; python_version >= '3.5'
208:sphinxcontrib-qthelp==1.0.3; python_version >= '3.5'
209:sphinxcontrib-serializinghtml==1.1.5; python_version >= '3.5'
212:sphinx-rtd-theme==0.5.0

rtd-requirements.txt
17:sphinx-git>=10.1.1
19:sphinxcontrib-fulltoc>=1.2.0
20:sphinxcontrib-websupport>=1.1.2
21:sphinx-rtd-theme>=0.5.0

**Comment by KSchopmeyer** [comment]
One of a number of discussions:

https://stackoverflow.com/questions/67542699/readthedocs-sphinx-not-rendering-bullet-list-from-rst-file

Issue filed on the theme itself:

https://github.com/readthedocs/sphinx_rtd_theme/issues/1115

It appears that the conclusion was that this is a theme issue but that it only appeared with docutuils 0.17.0.

**Comment by andy-maier** [comment]
It works everywhere when using docutils<0.17.

**DISCUSSION**: Do we accept that or continue investigating?

**Comment by KSchopmeyer** [comment]
It is not clear if the latest version 0.18.0 fixes the issue. If that were the case we could simply bypass 0.17.0.  Thus the question is whether we should create one more master for this release. My tendency is to try for one more and I will write pr

**Comment by andy-maier** [comment]
We concluded we are done with this one.
