### ISSUE TITLE
Some cmds that return no data on good completion return a statement rather than nothing

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#123]
Thus, for example, instance delete returns "deleted <instancname>

I propose that those commands that do not return anything should return nothing normally on succusful completion and return a statement (ex. the deleted ...) only in verbose mode.

Thus users who want to use the resulting data in in some way are not distracted by worthless data.

This applies to 

1. create
2. modify
3. delete

Note that we need to be sure that even the enumerates, etc. return nothing like empty return statements. Therefore, any of the commands that can return nothing need the verbose option that says "returned nothing"

**Comment by andy-maier** [comment]
This proposal needs to be updated and made more specific. For example, as of 0.5.0, "instance delete" does not display anything when successful.

**Comment by KSchopmeyer** [comment]
Karl: Describe the possible issues.  Do we want to have more output in verbose mode???

**Comment by KSchopmeyer** [comment]
The proposal would be that operations that return nothing would return a readable text stating success in verbose mode.   Note that we would not do this for create that returns the path itself and displays.

**Comment by andy-maier** [comment]
Fixed in PR #461.
