### ISSUE TITLE
The order of columns in the table output on Instance Get does not support the order requested

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#1259]
All of my scripts use Instance Enumerate, except my performance script which uses Instance Get to retrieve CIM_BlockStorageStatisticalData. Instance Enumerate works fine. But Instance Get reorders the columns requested. I consider this a minor error, but the order should be deterministic.
Here is an example from my script:
pywbemcli> instance get CIM_BlockStorageStatisticalData.? --pl InstanceID,ElementType,TotalIOs,KBytesTransferred -n device
Pick Instance name to process
0: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Array"
1: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Disk+0_0_0"
2: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Disk+0_0_1"
3: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Disk+0_0_2"
4: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Disk+0_0_3"
5: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Disk+0_0_4"
6: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Disk+0_0_5"
7: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Disk+0_0_6"
8: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Disk+0_0_7"
9: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+FEPort+SP_A:0"
10: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+FEPort+SP_A:1"
11: device:CIM_BlockStorageStatisticalData.InstanceID="ACME+CF2A5091300089+Volume+00005"
Input integer between 0 and 11 or Ctrl-C to exit selection: 0
Instances: CIM_BlockStorageStatisticalData
+-------------------------------------+-----------------------+-------------------------+-----------+
| InstanceID                                      | ElementType              |  KBytesTransferred [kB] |   TotalIOs |
|--------------------------------------+-----------------------+--------------------------+-----------|
| "ACME+CF2A5091300089+Array" | 2 (Computer System) |                                  66 |          132 |
+-------------------------------------+-----------------------+--------------------------+----------+

**Comment by KSchopmeyer** [comment]
Hmmm.  Something more complex is going on since a simple test as follows does order the properties correctly:

```
$ ppp -n mockassoc
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli> -o table enumerate TST_Person --pl Name,Likes,Gender
Usage: pywbemcli  [GENERAL-OPTIONS] COMMAND [ARGS] [COMMAND-OPTIONS]

Error: No such command 'enumerate'.
pywbemcli> -o table instance enumerate TST_Person --pl Name,Likes,Gender
Instances: TST_Person
+---------------+------------+-----------------------+------------+
| classname     | name       | likes                 | gender     |
|---------------+------------+-----------------------+------------|
| TST_Person    | "Gabi"     | 2 (movies)            | 1 (female) |
| TST_Person    | "Mike"     | 1 (books), 2 (movies) | 2 (male)   |
| TST_Person    | "Saara"    | 1 (books)             | 1 (female) |
| TST_Person    | "Sofi"     |                       | 1 (female) |
| TST_PersonSub | "Gabisub"  |                       | 1 (female) |
| TST_PersonSub | "Mikesub"  |                       | 2 (male)   |
| TST_PersonSub | "Saarasub" |                       | 1 (female) |
| TST_PersonSub | "Sofisub"  |                       | 1 (female) |
+---------------+------------+-----------------------+------------+
pywbemcli> -o table instance enumerate TST_Person --pl gender,Name,Likes
Instances: TST_Person
+---------------+------------+------------+-----------------------+
| classname     | gender     | name       | likes                 |
|---------------+------------+------------+-----------------------|
| TST_Person    | 1 (female) | "Gabi"     | 2 (movies)            |
| TST_Person    | 2 (male)   | "Mike"     | 1 (books), 2 (movies) |
| TST_Person    | 1 (female) | "Saara"    | 1 (books)             |
| TST_Person    | 1 (female) | "Sofi"     |                       |
| TST_PersonSub | 1 (female) | "Gabisub"  |                       |
| TST_PersonSub | 2 (male)   | "Mikesub"  |                       |
| TST_PersonSub | 1 (female) | "Saarasub" |                       |
| TST_PersonSub | 1 (female) | "Sofisub"  |                       |
+---------------+------------+------------+-----------------------+
pywbemcli> -o table instance enumerate TST_Person --pl gender,Likes,Name
Instances: TST_Person
+---------------+------------+-----------------------+------------+
| classname     | gender     | likes                 | name       |
|---------------+------------+-----------------------+------------|
| TST_Person    | 1 (female) | 2 (movies)            | "Gabi"     |
| TST_Person    | 2 (male)   | 1 (books), 2 (movies) | "Mike"     |
| TST_Person    | 1 (female) | 1 (books)             | "Saara"    |
| TST_Person    | 1 (female) |                       | "Sofi"     |
| TST_PersonSub | 1 (female) |                       | "Gabisub"  |
| TST_PersonSub | 2 (male)   |                       | "Mikesub"  |
| TST_PersonSub | 1 (female) |                       | "Saarasub" |
| TST_PersonSub | 1 (female) |                       | "Sofisub"  |
+---------------+------------+-----------------------+------------+

```

**Comment by FarmerMike252** [comment]
Yes, the instance enumerate works fine. The instance get does not.
