### ISSUE TITLE
Make code changes to fix pylint issue use-dict-literal

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1273]
This new pylint test looks for dict declarations of the form

    dict(a: 3, b: 4)

and proposes that they be changed to literals of the form:

    {"a": 3, "b": 4}

because the second form for defining a dictionary is significantly faster.  In pywbemtools we have hundreds of the dict(...) form that would have to be changed so we set pylintrc to ignore this for now.  Note that many of these pylint warnings fro the test defintions where dictionary creation is used extensively.  It is a significatnt task to change all of these pieces of code manually. Therefore the PR for this sets use-dict-literal as an issue to be ignored.

It would be better if we could at least fix the ones in pywbemtools and pywbemcli and set the pylint ignore into the test modules

**Comment by andy-maier** [comment]
PR #1271 disables use-dict-literal globally, and I think that is also the final solution.

Suggest to clsoe this issue as fixed.

**Comment by KSchopmeyer** [comment]
Propose move this to future version.**DISCUSSION**

**Comment by KSchopmeyer** [comment]
We propose to modify the solution in the future to require the fix for pywbemtools but leave the ignore solution for all of the tests.
