### ISSUE TITLE
Temp code for pywbem issue #1359 (leading colon in instance names)

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#131]
We inserted temporary code into _common.py parse_wbemuri_str that adds a : to a wbem uri if it is of the form class.<keybindings> to get around pywbem issue #1359.  

When that issue is resolved in released code, we can remove the test and change in parse_wbem_uri

**Comment by KSchopmeyer** [comment]
We concluded that this is an issue with pywbem 0.12.x.  We will not fix it in 0.12 but after the release of 0.13.0 we should make the minimum pywbem version 0.13.0 and remove the temp code.

**Comment by andy-maier** [comment]
As described in pywbem issue https://github.com/pywbem/pywbem/issues/1359, the fix was released in pywbem 0.13.0. Since pywbemtools requires one of the 0.14.x versions as a minimum, the workaround code can now be removed.

**Comment by andy-maier** [comment]
The fix in pywbem was released in pywbem 0.13.0 and is also in master (the upcoming 1.0.0). Since pywbemtools 0.6.0 requires pywbem 0.16.0 as a minimum, we can remove the temporary circumvention code in pywbemtools.

**Comment by andy-maier** [comment]
Addressed in PR #516
