### ISSUE TITLE
Tree output inconsistent ordering

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#135]
The tree output produces inconsistent ordering of objects. Here is an example from the same test in test_class_subcmd.py run multiple times. We should  be consistent so the same data produces the same result each time.

    # root
    #  +-- CIM_Foo
    #      +-- CIM_Foo_sub2
    #      +-- CIM_Foo_sub
    #          +-- CIM_Foo_sub_sub
    # or
    # root
    #  +-- CIM_Foo
    #      +-- CIM_Foo_sub
    #      |   +-- CIM_Foo_sub_sub
    #      +-- CIM_Foo_sub2

**Comment by KSchopmeyer** [comment]
I propose moving this to a future version

**Comment by andy-maier** [comment]
This issue was resolved in 0.6.0 with PR #515.
