### ISSUE TITLE
Click update to 7.0 breaks pywbemcli

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#137]
Click update to 7.0 causes pywbemcli to execute an exception each time a command is executed in the repl.

Here is a traceback

['Traceback (most recent call last):\n',
 '  File "/home/kschopmeyer/pywbem/pywbemtools/pywbemcli/pywbemcli.py", line 351, in repl\n
click_repl.repl(ctx, prompt_kwargs=prompt_kwargs)\n',
'  File "/home/kschopmeyer/.virtualenvs/pycli3tmp/lib/python3.4/site-packages/click_repl/__init__.py", line 224, in repl\n    group.invoke(ctx)\n',
'  File "/home/kschopmeyer/.virtualenvs/pycli3tmp/lib/python3.4/site-packages/click/core.py", line 1135, in invoke\n    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)\n',
'  File "/home/kschopmeyer/.virtualenvs/pycli3tmp/lib/python3.4/site-packages/click/core.py", line 641, in make_context\n    self.parse_args(ctx, args)\n',
'  File "/home/kschopmeyer/.virtualenvs/pycli3tmp/lib/python3.4/site-packages/click/core.py", line 1089, in parse_args\n    rest = Command.parse_args(self, ctx, args)\n',
'  File "/home/kschopmeyer/.virtualenvs/pycli3tmp/lib/python3.4/site-packages/click/core.py", line 940, in parse_args\n    value, args = param.handle_parse_result(ctx, opts, args)\n',
'  File "/home/kschopmeyer/.virtualenvs/pycli3tmp/lib/python3.4/site-packages/click/core.py", line 1477, in handle_parse_result\n    self.callback, ctx, self, value)\n',
'  File "/home/kschopmeyer/.virtualenvs/pycli3tmp/lib/python3.4/site-packages/click/core.py", line 96, in invoke_param_callback\n    return callback(ctx, param, value)\n',
'  File "/home/kschopmeyer/.virtualenvs/pycli3tmp/lib/python3.4/site-packages/click/core.py", line 861, in show_help\n    ctx.exit()\n',
'  File "/home/kschopmeyer/.virtualenvs/pycli3tmp/lib/python3.4/site-packages/click/core.py", line 504, in exit\n    raise Exit(code)\n',
'click.exceptions.Exit: 0\n'

**Comment by KSchopmeyer** [comment]
The easy solution until this is resolved in click is to change requirements.txt to disallow that major version change.   NOTE: this is the second time this year that we have hit issues with a major version change in a dependency.

**Comment by andy-maier** [comment]
Circumvented the issue in PR #141.
