### ISSUE TITLE
Travis Install fails with python 2.7 because of pywbem

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#14]
Travis CI fails with python 2.7 because M2Crypto install fails.  This is caused by a failure to
find a particular variable in OpenSSL during the install of pywbem.

ImportError: /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/M2Crypto/__m2crypto.so: undefined symbol: SSLv2_method

make: *** [install] Error 1

**Comment by andy-maier** [comment]
I have created PR #20 to see whether a particular change I found in the master branch of M2Crypto solves our problem. While PR #20 fails for other reasons, it does successfully get over the import of M2Crypto into pywbem.

So the M2Crypto code version in its master branch solves the problem for us. I have opened M2Crypto issue 165 (https://gitlab.com/m2crypto/m2crypto/issues/165) to request a new release of M2Crypto.

In the mean time, we could merge our PR #20 to use the master branch of M2Crypto to get our Travis runs and our users going again.

**Comment by andy-maier** [comment]
The final solution will then be:
- Wait until a new version of `M2Crypto` has been released on Pypi.
- Update `setup.py` of `pywbem` to require that new `M2Crypto` version, and release new fix versions of all supported stable versions of `pywbem` on Pypi.
- Update `requirements.txt` of `pywbemtools` to require that new version of `pywbem`.

**Comment by KSchopmeyer** [comment]
I committed Andy's temp fix but am keeping the issue open pending a permanent fix from the m2crypto people.

**Comment by andy-maier** [comment]
M2Crypto 0.26.0 contains the permanent fix for that. Both pywbemtools (as of PR #100) and pywbem (master) currently require M2Crypto>=0.24.0 (on non-Windows).

Need to verify Travis results for minimum package levels.

**Comment by KSchopmeyer** [comment]
Closed because of changes to pywbem.
