### ISSUE TITLE
Deprecate support for old-style mock scripts

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#1407]
pywbemtools 0.8.0 (released in 2020) introduced support for "new-style mock scripts". The support required running on Python>=3.6.

Nowadays pywbemtools requires Python>=3.8, so this ticket is to deprecate the support for old-style mock scripts. They would still be supported, but pywbemtools would issue some warning to the user indicating that support for old-style mock scripts is deprecated and will be removed in a future version.

**Comment by KSchopmeyer** [comment]
The deprecated warning code is already in the mock scripts __init__ function.  However we should extend the documentation of the fact that we have deprecated this functionality.
