### ISSUE TITLE
DIrections and Priorities for pywbemcli 0.5.0

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#165]
I propose that the initial release of pywbemcli be 0.5.0 (i.e.the initial release)

The primary goal for the first release was to:

1. Provide a command line interface for the pywbem server APIs.
2. Provide additional cmd line functionality for pywbem services like the WBEMServer class, and the subscriptionMgr class.  Possibly provide a subcommand to activate listeners.
3. Provide tools to make the cmd line easy to use including:
    a. selection rather than entering for things that are difficult to do on the command line (ex. enter instance paths)
    b. Provide a way that information about connections can be captured and stored for later use.
    c. Provide tools for visibility of  what is happening between the server and client (ex. the log)

**Open items:**

* DONE - Fix [mandatory issues for 0.5.0](https://github.com/pywbem/pywbemtools/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22version+0.5.0%22+label%3A%22release%3A+mandatory%22).
  Just for comparison: [open bugs for 0.5.0](https://github.com/pywbem/pywbemtools/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22version+0.5.0%22+label%3A%22type%3A+bug%22)

**DONE or MOVED items:**

* Code coverage at least 80%. Currently 77%
  Status: DONE. Coverage 89% as of 2019-09-23 (1 code PR to go before 0.5.0).

* Documentation review and clean up.
  Status: DONE. PR #162 and many other PRs.

* Review coverage to find functions that are completely not covered (i.e. real holes in the tests).
  Status: DONE. PRs #181, #180, #179

* Possibly expand tests for the connection subcommand.
  Status: DONE.

* Some important other issues:
  * #171 - DONE - This is apparently click issue
  * #140 - MOVED to 0.6.0 - No test for REPL mode. I do not see today how we can really test the REPL mode
  * #135 - MOVED to 0.6.0 - Tree output of instance inconsistent ordering. This affects tests sometimes, not users. Propose leaving open for future version
  * #130  - CLOSED as no issue - Documentation and help does not include examples
  * #124 - DONE - modify Instance subcommand.  This needs more tests.  (I propose that we not allow creating properties that are embedded instances for version 0.5.0 because that it a whole new level of input complexity.

**Functionality:**

* Functionality will include the subcommands for:
    a. class  - access a class and classes output mof, xml, repl mode.  No create or modify class.
  The subcommands include get, enumerate, associators, references, find, tree, invokemethod
    b. instance - access an instance or instances. Includes create and modify instances includes associators and references. Output as mof, xml, repl, table formats.  The subcommands include: associators, count, create, delete, enumerate, get invokemethod, modify query, references, shrub
    c. qualifier - access qualifier declarations, No create or modify. Output in mof, xml, repl, table formats
    d. connection - Define connections save to file, get by name, select/create/delete a connection in the file.
    e. server - get namespaces, interop, profiles. Get central instances
    f. repl - Execute in repl mode

* Functionality to move to 0.6.0:
   a. Subscriptions and indications - Create, list, delete subscriptions.
   b. Shrud display for associations.

* Status today
   a. **class** - Done except that there is no table output for classes. PROPOSAL: Return NOT IMPLEMENTED
   b. i**nstance** - Done with the above definition. InProcess:
      1. Shrub view  (WIP Pr now)    *Move to 0.6.0  
   c. **Qualifier** Declarations - Done 
   d. **connection** - Done with the following possible issues:
       1. Testing incomplete - Less than 80% coverage
   e. **subscriptions**  -(First cut in local draft now) Includes subscription list, basic create and delete of subscriptions.  ( Move to pywbemtools (o.6.0)
   f. **servers:** - done except: Testing limited (see PR #181)

**Code coverage when this issue was created (around 2019-06-07):**

```----------- coverage: platform linux, python 3.5.2-final-0 -----------
Name                                  Stmts   Miss  Cover   Comments
-------------------------------------------------------------------
pywbemcli/__init__.py                    21      2    90% 
pywbemcli/_cmd_class.py                 192     51    73%  - Pr # 180 move this to close to 80%
pywbemcli/_cmd_connection.py            175     64    63%  - Some increase with PR # 179
pywbemcli/_cmd_instance.py              290     56    81%
pywbemcli/_cmd_qualifier.py              34      0   100%   
pywbemcli/_cmd_server.py                106     71    33%   - pr # 181 moves coverage to between 70 and 80%
pywbemcli/_common.py                    523    108    79%   
pywbemcli/_common_options.py             16      0   100%   
pywbemcli/_connection_repository.py      92     24    74%   
pywbemcli/_context_obj.py                89     10    89%   
pywbemcli/_debugtools.py                 16     16     0%  
pywbemcli/_displaytree.py                32      1    97%   
pywbemcli/_pywbem_server.py             135     14    90%  - Some increase with PR # 179 
pywbemcli/_pywbemcli_operations.py       56      4    93%  - Some increase with PR # 179
pywbemcli/_version.py                    11      2    82% 
pywbemcli/config.py                      13      0   100%   
pywbemcli/pywbemcli.py                  106     18    83%  - Some increase with PR # 179
```

**Code coverage as of 2019-09-23:**

```
Name                                              Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------------
pywbemtools/pywbemcli/__init__.py                    22      2    91%   45, 47
pywbemtools/pywbemcli/_cmd_class.py                 192      7    96%   557, 592-593, 640, 658, 663-664
pywbemtools/pywbemcli/_cmd_connection.py            176      9    95%   355, 374, 410-414, 433, 449-450, 511
pywbemtools/pywbemcli/_cmd_instance.py              293     28    90%   593-595, 603, 619, 644, 650, 673-674, 692-693, 713, 725-727, 756, 829, 856, 873, 904, 919, 922, 926, 940-941, 962-963, 1003
pywbemtools/pywbemcli/_cmd_qualifier.py              33      0   100%
pywbemtools/pywbemcli/_cmd_server.py                116     17    85%   200, 219-220, 236-237, 252-253, 272, 282-283, 323-324, 355-357, 368-369
pywbemtools/pywbemcli/_common.py                    585     71    88%   50, 94, 111, 157-160, 183, 188-189, 194-195, 225, 240, 249-250, 303-304, 362-363, 406, 533, 535, 622-626, 630, 636, 670, 674, 751, 777, 861, 866-868, 874-875, 880-885, 903-904, 940-941, 963-965, 987, 1015, 1061, 1121, 1125, 1132, 1138, 1158, 1165, 1172, 1181, 1230-1232, 1281-1285, 1310-1314, 1371, 1466, 1473
pywbemtools/pywbemcli/_common_options.py             17      0   100%
pywbemtools/pywbemcli/_connection_repository.py     111     19    83%   68, 74, 99-103, 113-114, 120, 132, 151-152, 176-181, 231, 291
pywbemtools/pywbemcli/_context_obj.py               115     26    77%   55, 143, 181, 220, 226, 237, 242, 258-261, 270, 302-306, 335-341, 351-358
pywbemtools/pywbemcli/_displaytree.py                32      1    97%   54
pywbemtools/pywbemcli/_pywbem_server.py             163     20    88%   56, 65, 117, 138, 245, 247, 332-336, 343-353, 363, 438, 441, 459
pywbemtools/pywbemcli/_pywbemcli_operations.py       56      4    93%   282, 307, 322, 337
pywbemtools/pywbemcli/_version.py                    11      2    82%   48, 50
pywbemtools/pywbemcli/config.py                      13      0   100%
pywbemtools/pywbemcli/pywbemcli.py                  202     24    88%   288, 291-294, 343-350, 376-377, 391-394, 427-431, 433, 458-462, 479, 492-493, 547
-------------------------------------------------------------------------------
TOTAL                                              2137    230    89%
```

**Comment by andy-maier** [comment]
0.5.0 was released.
