### ISSUE TITLE
Remove use of pbr

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#178]
Per our discussions on 28 June 2019, the question is open also for pywbemtools whether we should eliminate the use of pbr.

**Comment by KSchopmeyer** [comment]
We concluded that we will release v 0.5.0 without this change and consider both pywbem and pywbemtools change for pbr in next release (0.6.0 for pywbemtools)

**Comment by andy-maier** [comment]
Just for completeness, here are the main reasons to drop pbr:
  - Getting the minor version increased in a development version (instead of
    the patch version) by means of markers in the commit message never worked.
  - The package needed to be tagged twice during the release process.
  - If the last tag was too far in the past of the commit history, the
    shallow git checkout used by Travis failed and its depth needed to be
    adjusted. At some point this defeats the purpose of a shallow checkout.

**Comment by andy-maier** [comment]
Addressed by PR #517.
