### ISSUE TITLE
No way to capture output with simplified_test_function

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#182]
While this is not an issue with pywbem it is with pywbemtools because so much of the function results are actually stdout.  In pytest the fixture capsys must be defined on the test function to enable stdout capture and this does fit into the fixed structure of the simplified_test_function definition.

**Comment by andy-maier** [comment]
PR #564 is going to address this issue.

**Comment by andy-maier** [comment]
I have tried to migrate the `simplified_test_function` decorator to use the `wrapt.decorator` approach provided by the wrapt package. Reason for that was the claim of wrapt that they are the most truthful decorator package.

At first, I tried to migrate to wrapt without solving the problem of adding support for additional fixtures. This migration was not successful. Manual invocations of test functions decorated with `simplified_test_function` worked fine, but pytest reports an error during collection of testcases:
```
In test_is_classname: function uses no argument 'desc'
```
I have verified via `inspect.getargspec()` that the argument specification of the decorated test function is as expected, i.e. `desc` as the first argument. Nevertheless, it seems that pytest does not look at the argument spec, but gets its information somehow differently. I did not find out how to solve this, and have given up on using wrapt.

**Comment by andy-maier** [comment]
I have made another attempt to add support for additional args when a function uses the `simplified_test_function` decorator. This was also not successful so far. Details are in branch [stf-add-args](https://github.com/pywbem/pywbemtools/compare/try/stf-add-args).

**Comment by andy-maier** [comment]
I have given up on the approach in PR #564 to extend the simplified_test_function decorator to support additional arguments. PR #625 addresses this issue here by removing the use of the simplified_test_function decorator on the test function in question.

DONE - addressed in PR #625
