### ISSUE TITLE
Add JSON output format

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#184]
Add the ability to ouput as json.  Note that this might not be as simple as it sounds since this could include json table but also json as an output form for the tree.

**Comment by andy-maier** [comment]
**DISCUSSION**:
* Are we serious with this item?
* Should the JSON representation from [DSP0211](https://www.dmtf.org/sites/default/files/standards/documents/DSP0211_2.0.0.pdf) be used?

**Comment by andy-maier** [comment]
We deicded that we are serious about it, and to start with looking at DSP0211.

**Comment by andy-maier** [comment]
We discussed this again and now decided that we would wait for user requests before we engage there. Closed as won't fix.
