### ISSUE TITLE
Remove sort option from many commands.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#247]
We use the sort option to organize the order of output in several cases but in particular in instance and instance name output.  In general we sort the instance path before we output.  However it is not like we are sorting from one known order to another order (i.e. sort on col 1) but we are sorting from random order received from server to sorted by order of the paths.

I propose that we remove the --sort option for all of the instance, class, and qualifier operations and just sort the objects.

The only negative I can see here is that it could take time to sort very large outputs but it is also going to take much more time to just display them.

This means removing the -s --sort from several of the commands.

**Comment by andy-maier** [comment]
Fixed in PR #254
