### ISSUE TITLE
Docs: Clarify differences between expected output fmts and received

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#248]
Clarify the issues in where you can ask for a specific format and get somethiing else.

Thus, 
we do not have a table output for class enumerate, etc. so we output mof
we force a tree output for class tree
even if mof is the default we do not try to output tables of namespaces, profiles, as MOF.

**Comment by andy-maier** [comment]
I think we should determine the exact list of cases where we use a different output format than the one that was requested.

**Comment by andy-maier** [comment]
Some clarification was done in PR #262, but review of the remaining issues is needed

**Comment by andy-maier** [comment]
PR #262 was merged without much of a review on my end. I think the description of the `--output-format` general option needs a few updates, and I have done that in PR #272, which fixes this issue here completely.
