### ISSUE TITLE
Replace short options with abbreviated long options

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#250]
Copied from issue #241:

* Andy: The short option names for the subcommand options are very hard to remember, given how many of them there. There are several occasions where upper case is needed to distinguish options that would abbreviate to the same short letter, or unintuitive short names, such as `-C` for `--resultclass`. Combined with the fact that we have no consolidated help showing both the general options and subcommand options in the same place, it is very hard to remember the short options. Also, I found some reuses of short option names, for example: `-o` is the short name for both the general option `--output-format` and the subcommand option `--names-only`, or `-s` means `--sort` in `class associators` and `--superclasses` in `class tree` and `--scoping_class` in `server centralinsts`. There are several more reuses of short names. I think specifically the `-o` reuse indicates that it is too complex even for ourselves.
  I have these suggestions to improve that:
  a) Drop the short names for all subcommand options.

* Karl: I have no problems with b) but I seriously worry about removing all short names on the subcommand options since the goal of short names was to make it easier for the frequent user. Maybe we remove short names on some of the less frequently used and maybe we can simply remove some options like sort and just do it always since not sorted means nothing in most cases (i.e. no really known order)  Also I really hate the -o/--namesonly since the short name does not match the long name. I will make a proposal tonight.

* ANdy: We discussed the idea to use abbreviations in the log option format, e.g. `--iq` for `--include-qualifiers` etc. That would allow removing the short options, and the new abbreviated long options would be much more systematic. Would be done in a separate PR.

**Comment by andy-maier** [comment]
Proposed rule: If an abbreviation of a long option results in a single character, a short option is used. If it results in more than one character, these characters form a second long option.

Example for `class associators`:
```
  --ac, --assoc-class CLASSNAME
  --rc, --result-class CLASSNAME
  -r, --role PROPERTYNAME
  --rr, --result-role PROPERTYNAME
  --nq, --no-qualifiers
  --ico, --include-classorigin         # maybe --include-class-origin ?
  --pl, --propertylist PROPERTYNAME    # maybe --property-list ?
  --no, --names-only
  -n, --namespace NAMESPACE
  -s, --summary
  -h, --help
```

**Comment by andy-maier** [comment]
Karl prepares a PR for this one.

**Comment by KSchopmeyer** [comment]
submitted as pr # 310
