### ISSUE TITLE
Docs: Move sections on pywbemcli command into one section

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#255]
Sections 2, 3, 4, and 5 are all about pywbemcli.

If we add a second command, we probably would like to have those sections be subsections of a single H1 section named "Pywbemcli command".

We might want to do that already now, even though we have only one command. This would suggest to increase the number of heading levels shown in the TOC from 2 to 3.

**Comment by KSchopmeyer** [comment]
Since we do not have a second command right now, I propose we move this to the next revision.  Since it is documentation, there is no backward compatibility issue.
DISCUSSION

**Comment by KSchopmeyer** [comment]
Moved to 0.6.0

**Comment by andy-maier** [comment]
Addressed by PR #445.
