### ISSUE TITLE
option to allow selection of pull/non-pull operations

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#26]
Today pywbemcli exclusively uses the original enumerate operations, It does not use the pull or iter commands at all.

I would like to change it to always use the iter commands since that allows us the freedom to use pull when possible.  I propose also to add one option so that the user could select use of either pull or non pull since that would provide a test of pull vs. non-pull operations

**Comment by KSchopmeyer** [comment]
This is part of a bigger issue.  Right now we build the pywbem calls right into the the cmd action functions. However, as we incorporate stats and logs we may need to generalize a set of functions so that there is a single point where the pywbem apis pass to make working with logs and stats easier.  This would then mean we also would have a single point for each of the enum commands that would implement the iter function with parameters.

**Comment by andy-maier** [comment]
Fixed by #40.
