### ISSUE TITLE
On Windows Builddoc only picks up the first help

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#264]

**Comment by FarmerMike252** [comment]
Under Windows it appears that the Builddoc routine is only collecting the help information for the pywbemcli, but cannot find the files for the other commands.

**Comment by KSchopmeyer** [comment]
We are missing a develop prerequisite on the builddoc target so that if builddoc is the first make call aon a new envrionment, the prerequisite tools (in this case chmod) is not installed.

**Comment by andy-maier** [comment]
Fixed with PR #268.
