### ISSUE TITLE
Builddoc failed when it was the first command after a clone (on Windows)

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#265]

**Comment by FarmerMike252** [comment]
The issue showed up as builddoc could not find chmod.

**Comment by andy-maier** [comment]
Hi Mike, I have fixed it in PR #274, but have not yet tested it on Windows.

**Comment by FarmerMike252** [comment]
Thanks Andy.

**Comment by andy-maier** [comment]
Great! PR is merged to master.
