### ISSUE TITLE
MaxObjectCount is interpreted as a string on Windows

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#298]
MaxObjectCount is being interpreted as a string (instead of an integer) on Windows. I tried by passing this error by specifying --use-pull no and resetting --pull-max-cnt 90. But some how the  pywbemcli is still trying to use MaxObjectCount and interpreting it as a string. The session and the error that I got is shown below:
C:\Users\FarmerMike>workon pycliclone
(pycliclone) C:\Users\FarmerMike\devenv\pycliclone\pywbemtools>pywbemcli --mock-server MockLoad.py --default-namespace root/cimv2 --use-pull no --pull-max-cnt 90
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli.
pywbemcli> connection show
-
name: default
  server: None
  default-namespace: root/cimv2
  user: None
  password: None
  timeout: 30
  no-verify: False
  certfile: None
  keyfile: None
  use-pull: False
  pull-max-cnt: 90
  mock-server: C:\Users\FarmerMike\devenv\pycliclone\pywbemtools\MockLoad.py
  log: None
pywbemcli> instance enumerate CIM_RegisteredProfile
/Getting classes for the SNIA Server
Getting classes for  SNIA_Array
|Loading classes into the Mock Repository
|Loading instances into the Mock Repository
Error: instance enumerate failed because FilterQuery not allowed with traditional EnumerateInstance. --use-pull: False. Exception: ValueError: MaxObjectCount must be > 0 but is False
pywbemcli>

**Comment by andy-maier** [comment]
Addressed in PR #308.
