### ISSUE TITLE
Change connections file per discussions.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#299]
We proposed some changes to the connections file.

1. Change to use YAML. Currently the connections file is in json format.

We are probably safer with YAML so we will change toe format to YAML.

2. Change the name of the file to pywbemcli_connections.yaml

**Comment by andy-maier** [comment]
Karl, in PR #295, you documented the agreement from our meeting as follows:
1. Use pywbemcli_connection_definitions.json for the file name.
2. Use "WBEM connection definitions" and remove the word "persistent".

I have no problem with changing the agreed file name to what you now used, but I think we should stick with the term "WBEM connection definition" or short "connection definition". I have made according comments on PR #301.

**Comment by andy-maier** [comment]
Addressed by PR #301.
