### ISSUE TITLE
Add logging functions

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#3]
We can initially use logging to capture:

1. Calls to pywbem and even the debugging responses

2. Debugging features that could be enabled or disabled

Suggest that a useful

We should discuss further usage.

DISCUSSION: Should we consider using the click logging contrib?

**Comment by KSchopmeyer** [comment]
We want to be able to log both the pywbem api calls and the wire interface.  Both of these, however should be within pywbem so the primary function here would be to control the logging in pywbem.
Start pywbem issue on logging.

Discussion: Should we log all commands, i.e. what the command and options were that was executed.

**Comment by andy-maier** [comment]
**Discussion point:** Has this been addressed by PR #125 ?

**Comment by KSchopmeyer** [comment]
C
