### ISSUE TITLE
Create a tool/support extension that will automate outputting overall help info.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#30]
Issue: While help is easy to view on a piecemeal basis, these programs become big enough that it is difficult to view the commands/groups/subcommands in an overall context and to actually search for information.

Goal: A tool or extension to click that will create output that represents a complete set of the help for an application like pywbemcli.   This would output the help for every command and group.

There are two ways to do this:

1. Imitate what the click man page contrib did by extending setup so that the file is created through the setup functions.

2. Add another component to help so that we end up with some sort of new command or option on help to do help with some options (ex. all).

**Comment by KSchopmeyer** [comment]
One possible solution to this is https://github.com/click-contrib/sphinx-click.  Have not looked any further than knowing that it allows integrating click help into your sphinx doc.

**Comment by andy-maier** [comment]
Addressed in PR #53.
