### ISSUE TITLE
Docs: Change command descriptions to become sections

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#313]
The command groups have sections:
* 4.2. Class command group
* 4.3. Instance command group
* 4.4. Qualifier command group
* 4.5. Server command group
* 4.6. Connection command group

However, the commands within these command groups are list items within the text.

Issues with that:
* They cannot be referenced.
* The TOC for section 4 does not show them.

Proposal:
* Change the command descriptions in these sections to become sub-sections.

**Comment by KSchopmeyer** [comment]
I  agree.

**Comment by andy-maier** [comment]
Addressed by PR #319.
