### ISSUE TITLE
Modify so we use general options in interactive mode

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#335]
Modify startup and command setup so that we use the general options for connections (--server, etc. in interactive mode as well as at startup.  This involves two changes.

i. Process all of the options to the cli method on all calls, not just the initial call.
2. Modify Pywbemcliserver class to do clean modification of parameters as well as init.
3. Modify the code in the cli function that processes commands in interactive mode so that it processes all input parameters to cli and sets them into the current context.

NOTE: The goal is to use general options only for the current command execution, not to make them the norm for succeeding commands in the interactive session.

**Comment by andy-maier** [comment]
Will be addressed by PR #336.
