### ISSUE TITLE
Comments on doc as of pr #351

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#353]
Updates by Andy: This issue is addressed by PR #378, and the updates marked AM> describe how it addresses the item.

**Section 2**

1. Section 2.2, lCommand mode. We can remove "Pywbemcli uses the Python click package for its command line handling. ". It is the next sentence that is important.
   AM> **NOCHANGE** - I agree that the second sentence is the important one, but the first sentence motivates why we refer to the bash completion of the click package (as opposed to any other description).

2. Section 2.3 "an interactive shell environment is within pywbemcli that allows typing pywbemcli commands". Remove "is" before within.
   AM> **DONE** - Changed to "pywbem provides an interactive shell environment that allows...".

3. Section 2.3, line 156.  "The commands that can be typed in the pywbemcli shell are the rest of the command line". The example below this line shows the [GENERAL-OPTIONS] but the text does not mention them.
   AM> **DONE** - Changed to "The commands and options ..."

4. in the section 2 overview we define things like COMMAND-OPTIONS and ARGS but do not define what separates ARGS from command options.
   AM> **DONE** - The text there already says "Options are prefixed with the characters `-` for the short form or `--` for the long form...". To make this double proof, added "The other components do not begin with ``-``." to that first sentence.

**Section 3**

1. Section 3.3.14, --mock-server general option. Change "This option may be specified multiple times." to:
   This option may be specified multiple times to define multiple MOF and Python files that make up the definition of a mock-server.  The files must have the suffix ".mof" for MOF files and ".py" for Python scripts.
   AM> **DONE** as proposed.

2. --mock-server environment variable - We do not define how to implement an environment variable with multiple items.  Click sort of documents this as having space between each item. PS: I would not panic with this one.
   AM> **DONE** - Added a note (1) to PYWBEMCLI_MOCK_SERVER with this text: "(1) The `--mock-server` general option can be specified multiple times. To do that with the PYWBEMCLI_MOCK_SERVER environment variable, separate the multiple path names with space.". I also verified that this actually works (it does).

3. In section 3.7, the sentence "Note: The * indicates that this is the current connection." should be expanded to show both the current and default
   AM> **DONE** - The * was actually incorrect, because saving a connection no longer makes it the current connection. Fixed that, and reworked the examples in section 3.7 significantly.

**SECTION 4**

1. The section titled "Specifying CIM property and parameter values" is not complete.  Proposal submitted as PR #391.
   AM> **DONE** by PR #391.

**SECTION 5, GENERAL**

1. Some day we should probably define associators and references but not for this version.
  AM> **NOCHANGE** - not clear what you mean? You may want to open an issue describing what you mean.

2. It is confusing that we don't show the syntax of the command here but it does appear in the
   '...details we point to.
  AM> **NOCHANGE** - I also think that having the help messages in a separate section is not optimal, but I don't think we need to change this now. You may want to open an issue on that.

3. I agree with Andy that the phrasing See ... for details is misleading.  Probably should be see ... for the exact help ouput for the command.
  AM> **DONE** - Changed "See <pywbemcli ... –help> for details." to "See <pywbemcli ... –help> for the exact help output of the command." throughout section 5.

4. The sections defining commands are ordered alphabetically. Should we reorganize them to break out functionality groups (create, modify, get, delete, enumerate) (references, associators), invokemethod, and finally those that try to organize the server information like count????
   NOTE: I have no issue putting that kind of thing off to next release.
  AM> **NOCHANGE** - not in this release. If you really want that, open an issue.

5. Argggh: I almost think that we should have used the command name list in place of enumerate. Why write something long and slightly obtuse.  NOTE: Future we can alias command names like that.
  AM> **NOCHANGE** - I'm ok with adding a "list" command alias in a future release. "enumerate" is known to many users, so replacing it with "list" may not be the best choice.

**COMMENTS ON COMMANDS in section 5**

1. Section 5.1.6.  Class Invokemethod needs example.
   AM> **DONE** - added working example with AllTypesMethod.

2. Section 5.2.1, Instance associators command.
   Should note that 'class associators command' shows classes associated with CLASSNAME'
Same for the 'Instance references command'
   AM> **DONE** - added for both.

3. Section 5.2.8: Instance modify command:
   a) We do not mention the property list option and should probably describe what server does with this and the properties.
      AM> **DISCUSSION** - The PropertyList parameter on the ModifyInstance CIM-XML operation is a complication that should never have been there in the first place. I don't think that very many providers have actually implemented what DSP0200 ended up saying on it. I hope we can avoid that complication i.e. the use of the --propertylist option completely for the "instance modify" command, but I'm not sure we are there. Need to discuss.

   b) Also add note that you cannot modify key properties.
      AM> **DONE**

4. Section 5.2.10. Probably need to point to DMTF spec for CQL.  Also, the DMTF:CQL in second paragraph should probably be a :term: that can point to the spec.
   AM> **DONE** - added reference to new CQL term and added CQL term that references the DSP0202 spec.

5. Section 5.5.1, Connection Delete Command.
Second example:  "Input integer between 0 and 2 or Ctrl-C to exit selection: 1  << users enters"
Should be "user enters"
   AM> **DONE** - changed to "<< entered by user" for all examples with prompting.

**No comments on section 6, 7, 8 or 9.**

**Comment by andy-maier** [comment]
Issue descriptions need to be completed by Karl.

**Comment by andy-maier** [comment]
Addressed by PR #378.

**Comment by KSchopmeyer** [comment]
Conclusion:  We discussed the propertylist on modify linstance and agreed to leave it in but add statement about why not to use it.
