### ISSUE TITLE
Documentation defining good vs error responses

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#357]
I made a mistake in putting statements in specific command about good vs. exception responses.  Things if successful returns ... or exception.  I think we should make the statement once about the commands that if unsuccessful they return exceptions received from the server or from pywbem interpretation of the response data and let it go at that.  Then remove anything from individual commands about unsuccesful responses except in those cases that differ from this general policy.

**Comment by andy-maier** [comment]
I think that should be in a section "Error handling" somewhere.
We should describe that incorrect parameters cause the command to fail, and that errors returned from the WBEM server also cause the command to fail, and how these two cases can be distinguished. Also we should mention the command return code.

**Comment by andy-maier** [comment]
I can take this one on.

**Comment by andy-maier** [comment]
Addressed by PR #370.
