### ISSUE TITLE
Move table support library from ascii-table to tabulate

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#36]
I originally chose asciitable specifically because it supports multiline cells.   Since it appears that tabulate package supports multiline tables and has a much wider set of output formats, I propose switching to use the tabulate package.   

Luckily, the general form of the data input is largely the same so the actual change should be minimal.

**Comment by KSchopmeyer** [comment]
Having tested the feature branch for multiline columns of tabulate, I have found several problems which I am feeding back to the author as comments on the issue.  This is largely built around problems with the column widths where columns where the data in the columns is longer than the header name for that column and the first row for that column is an empty string, cause problems in formatting.

https://bitbucket.org/astanin/python-tabulate/issues/28/feature-request-multiline-cells-and

and the formatting is incorrect for some table types with just multiline tables, in particular the rst format.

**Comment by andy-maier** [comment]
This one is now superceded by issue #95. Closing this one.
