### ISSUE TITLE
"server connection" not consistent with "connection show"

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#360]
The "server connection" command and the "connection show" command both display information about the current connection.

However, they show different fields that partly have different values:

```
$ pywbemcli --name mymock server connection
-
url: http://FakedUrl
creds: None
.x509: None
default_namespace: root/cimv2
timeout: None sec.
ca_certs: None

$ pywbemcli --name mymock connection show
-
name: mymock (current)
  server: None
  default-namespace: root/cimv2
  user: None
  password: None
  timeout: 30
  verify: True
  certfile: None
  keyfile: None
  mock-server: tests/unit/simple_assoc_mock_model.mof
  ca-certs: ['/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt', '/etc/ssl/certs', '/etc/ssl/certificates']
```

That should be made consistent both regarding the fields and regarding the values shown.

**Comment by KSchopmeyer** [comment]
The alternative is to drop the server connection command since it is the same as the connection show.

**Comment by KSchopmeyer** [comment]
I put the server connection in early before we really developed the connection show command.  I think I need to justify to myself why we still need it.

**Comment by andy-maier** [comment]
I agree with dropping "server connection". Go ahead.

**Comment by KSchopmeyer** [comment]
Done. and submitted as PR # 369
