### ISSUE TITLE
the command get-centralinsts; should it be centralinsts or central-insts?

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#367]
all of the other commands in server use only the name of the object. profiles, namespaces, interiop.  For some reason I put get- on the centralinstances so that it is "get-centralinsts" instead of the more consistent "centralinsts".

Should we change the name of the command to centralinsts.??

**Comment by andy-maier** [comment]
I agree, I already had the same thought. Go ahead!

**Comment by KSchopmeyer** [comment]
Will change name to central-insts with the dash as word separator

**Comment by andy-maier** [comment]
Adressed by PR #371
