### ISSUE TITLE
Mock repo reset after each command in interactive mode

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#375]
We clear the wbem server for each new command, not just when we are modifying the inut parameters.  This means that if you delete an instance in interactive mode, it pops up again for the next interactive command because clearing the server also clears the repository.

Must clean up the clearing of the server and repo even in the case where we are modifying some parameters.

**Comment by andy-maier** [comment]
I think that one major purpose of the interactive mode is to be able to run multiple commands against the same mock repository. For a real WBEM server it does not matter if the connection is re-established on each command, but for a mock server it does matter.
Bottom line: I think it would be good if we could address this in 0.5.0
