### ISSUE TITLE
Clarify --propertylist option on instance modify

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#399]
We include the option but do not give any information on its use. 

First we concluded that it is close to useless from the command line.  The only case it makes sense is when the user gets the instance from the server, modifies the instance and then returns it without removing properties that were not modified.  That is not our case, we are building the instance with just the properties defined.  

Second, Andy feels that there may be servers that did not implement it.
Update by Andy: No, I feel that about the latest twists on ModifyInstance in DSP0200 that have to do with default values and NULL.

Third, through the various versions of the spec, there was confusion over exactly what it did.

The conclusion is that we will leave it it but clarify that it should be of no use to cmd line users or something to that effect.

**Comment by andy-maier** [comment]
PR #402 addresses this, plus a minor docs fix and some more consistency improvements on --propertylist.
