### ISSUE TITLE
Version 0.5.0. class find --help shows --namespace option twice

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#417]
Options:
  -n, --namespace NAMESPACE  Add a namespace to the search scope. May be
                             specified multiple times. Default: Search in all
                             namespaces of the server.
  -n, --namespace NAMESPACE  Add a namespace to the search scope. May be
                             specified multiple times. Default: Search in all
                             namespaces of the server.

**Comment by andy-maier** [comment]
I grabbed this one.

**Comment by andy-maier** [comment]
PR #425 fixes that for master, and PR #426 for 0.5.1.
