### ISSUE TITLE
Add command to get information on DMTF schema used by server

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#444]
I propose that we add a command to get whatever information is available on the DMTF schema implemented including best guess at the schema version, and any other information we can gather about the schema.

Per a pywbem user issue (pywbem issue # 1896), there is interest in getting this info

**Comment by andy-maier** [comment]
This could be done by examining the Version qualifier of all CIM_* classes and taking the maximum version found.

**Comment by andy-maier** [comment]
For the command, I think we should not add more stuff to the "server" command group, but probably should add a new command group "schema" with command "info".
