### ISSUE TITLE
Find means to show classes filtered by characteristics

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#447]
In workin with the command line it is often useful to be able to filter classes/classname returned by particular characteristics like associations only all non-association classes.  

The questions are;

1. What would be good criteria for filters
2. How could we incorporte filters into the cmd line

**Proposal one:**
Add an option that would defined a filter that would filter the classes returned by particular class qualifiers.  Thus, it would be able to ask for classes that were assocaitions or not associations, etc.  This does not mean that we would want to use all possible qualifiers as filters so I am not sure today if the idea of something that would filter by filtername/value that allows all qualifiers is the correct solution but it is one possible solution.

Thus the filter could be something like

--filter association=Ture --version >2.45.0

Note that only a few of the qualifier declarations are really used at the class level including: Abstract, Association, Description, Version, UmpPackagePath, Aggradation, Composition, Indication, Deprecated, Experimental, 

Note also that adding this to something like class enumerate causes other issues with the use of class enumerate as a direct access to the CIM/XML enumerate/enumeratenames requests in that if this fiter was to be used, it would mean that the --no opetion could not be used directly since the full class would have to be retrieved to process the filter.

**Comment by andy-maier** [comment]
I think characteristics filters should be supported on:

- all operations that return classes or instances (including if just their names are returned).

and could support the following filters, stated in terms of options (probably to be prioritized):

- `--association`, `--no-association`
- `--aggregation`, `--no-aggregation`
- `--composition`, `--no-composition`
- `--indication`, `--no-indication`
- `--schema={schema}`
- `--version{op}{version}`
- `--deprecated`, `--no-deprecated`
- `--experimental`, `--no-experimental`

These filters would need to take into account the **effective** values of the respective qualifiers, in case they are based on qualifiers.

**Comment by andy-maier** [comment]
After discussion, it seems a first stage would be:

Filter:
- `--association`, `--no-association`
Commands:
* `class enumerate` (with and without `--names-only`)
* `instance enumerate` (with and without `--names-only`)
* `instance count`

**Comment by andy-maier** [comment]
Addressed by PR #456.

**Comment by andy-maier** [comment]
**Discussion point:** What are the next stages and do we handle them in this issue or in a new one?

**Comment by KSchopmeyer** [comment]
We agreed to do:
1. Deprecation.

2. --schema={schema}, maybe --no-schema={schema}, maybe --classname={classname-pattern}

3. --superclass={classname-pattern}, --no-superclass
   Consider separating direct superclass from general inheritance.

We will stay with the existing set of commands that implement filtering.

**Comment by KSchopmeyer** [comment]
Moved to 7.0

**Comment by KSchopmeyer** [comment]
We did not add any filters in vers 0.7.0 but moved that work to 0.8.0.  We propose to add at least the following in version 0.8.0

1.    Deprecated classes

2.    --schema={schema}, maybe --no-schema={schema}, maybe --classname={classname-pattern}

3.    --superclass={classname-pattern}, --no-superclass
    Consider separating direct superclass from general inheritance.

See issue #678 for the work to be done in pywbemcli 0.8.0

**Comment by andy-maier** [comment]
**DISCUSSION*: Scope of this issue for 0.9.0

**Comment by andy-maier** [comment]
Issue #682 covers `--schema` and `--superclass`.

The remaining potential filters are then `--aggregation`, `--composition`, `--version{op}{version}`, and at this point we don't think we will implement them.

**Comment by andy-maier** [comment]
Support for version is implemented with a `--since` filter option in PR #682.

That leaves only `--aggregation` and `--composition` from the original list. We discussed this and decided they should not be implemented (for now).
