### ISSUE TITLE
instance associators/references tests with wildcard keybindings fail

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#458]
We have two tests that use mock prompt that started failing on some versions of python when we moved to use python 0.15.0 (Note that this may not even be tied to that version but the failures started when we started testing with this verrsion of pywbem).

These fails are marked with this issue number in test_instance_cmds.py

**Comment by andy-maier** [comment]
Not clear when the issue was fixed, but PR #656 removed the TODO for this issue and verifies that the testcase now works (with 0.7.0 dev). Considering this issue as fixed.
