### ISSUE TITLE
Connection repository is difficult to read because of terminal width

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#462]
The normal output for the connection repository is a table format to the console and, at least for me, the most frequent use it to look up the names of connections with minimal extra information to clarify the names.

However, the display is very wide because it displays almost all the informtion in the table so that a simple connection list is very messy to read on the terminal.

There are several solutions to this possible including:

1. Modify pywbemcli so that tab complete would operate against the -n option. Note that this is beyond the scope of the built in auto-complete functionality since that only operates against the command names in the script mode.  

The click-addon, click-completion probably forms the basis for a more complete auto completion mode.

2. Modify the connection list command to produce a table more consistent with the width of the display.  This would mean producing a table output with a few rows in the 80 col mode or wider as the terminal was made wider.  Note also that this would probably mean ignoring the width definition if the HTML output was set.  Also there should be an option to override the width and display the current output even if it exceeded the terminal width.

**Comment by andy-maier** [comment]
PR #575 (in 0.6.0) changed the behavior so that by default, only 3 columns are shown in `connection list`. The full set of columns can be shown using a `--full` option.

**Discussin point:** Given that, what is left to be done from this issue?

**Comment by andy-maier** [comment]
We agreed that nothing is left to be done.
