### ISSUE TITLE
Document use of click autocomplete with powershell.

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#478]
We have documented how to use auto complete from bash at least based on the documentation in click

However, on windows  cmd.exe has no support for concepts like auto complete. Powershell does and a lot of our users are windows based developers so it behoves us to try to figure out how to use the auto-complete with powershell.  Note that the current click documentation does not give any clue.  However,  click contrib  https://github.com/click-contrib/click-completion(), there is auto completion, they have a complete example of using their extension and adding a command.command group so the user can setup the auto compete from within the click application.

This might be the way to include auto complete for power shell and also to move it from just a set of instruction to part of pywbemcli.

I propose we consider this for version 0.6.0

**Comment by andy-maier** [comment]
We discussed this and decided to not do it, because it does not seem to be supported in click for powershell.
