### ISSUE TITLE
Add the capability to inspect jobs

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#5]
Note that this would probably involve both pywbem and pywbemcli.  It would be more logical to add the jobs class itself to pywbem and the usage to pywbemcli.

The goal would be to gather information on jobs existing and provide access to the methods that control executing/killing jobs.

**Comment by KSchopmeyer** [comment]
This may only make sense if we add the capability to pywbem first.

**Comment by KSchopmeyer** [comment]
**DISCUSSION** Agreed.  I propose that we close this Issue

**Comment by andy-maier** [comment]
We discussed this and agreed on dropping this one.
