### ISSUE TITLE
Clean up display output to better output information as tables

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#50]
Today the output is a mishmash.  We want to output data as tables with headers wherever possible and to allow multiple table structures.   We wanted to use tabulate since this flexibly handles tables but it does not handle multi line cells and we will require that. 

Therefore, it would seem that the best solution for now is

a. Accept the tabulate table structure types, and switch to   tabulate for table generation
b. If we need multirow cells, take some of the work from another project that does produce multiline cells but does not have all of the options of tabulate and use it when we specify tables as multiline rows.

I am trying to sort out the relation between output formats and what gets produced.  This is made more difficult for the user to understand because we have both data output that it clearly display table oriented 
(lists and lists of lists) and an data that has an internal structure that we want to present (CIMInstance, etc.). Clearly not all of the output forms apply to all of the possible output.  Thus, 'mof' as an output type only applies to a CIMInstance, etc. data.  Table and the various table forms applies to both lists, and objects. We present instances/classes as a table (properties as columns). But if we use the 'html' type, it
is unclear what we mean.  In fact today what we mean is html table of the properties, not an html representation of the CIM Instances.

Right now the output formats are ['mof', 'xml','table', 'plain', 'simple', 'psql', 'rst', 'mediawiki', 'html']

Where all of the names are for table display except for mof and xml which only apply to CIMInstance, etc. and table, plain, etc. apply also at least to CIMInstance.  CIMClass it is clear probably mostly makes sense
as MOF or xml (or future htmlMOF)

Right now, it accepts table, html, etc. for any data that can be displayed as a table including CIMInstances
and forces CIMClasses to mof unless outputformat=xml irrespective of the defined output type.

DISCUSSION: Have we picked the output types correctly with this overlap and confusion.
```
Data types cimInstance/CIMClass/CIM/Param       CIMObjectName               Data Lists(namespaces, etc)   
Formats     This is a complex structure                   Normally displayed           List or list of lists
                                                                             as list

MOF                          Yes                                       No                                     No

XML                           Yes                                      Yes                                     No

Table              Instance Properties                          Not sure                             Yes
simple,
etc.

HTMLTable     Instance Properties                          Yes                                     No
                     (same as table above but
                     in html)

HTML           HTML form of mof,                          Not sure                             Yes, table rendered in html
data             (Future)
```

**Comment by andy-maier** [comment]
Addressed in PR #54.
