### ISSUE TITLE
make develop in new environment cannot import click on first try

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#51]
For some reason running develop in new environment has a problem with the click install but it works the second time.  I assume there is an ordering problem in requirements.txt.

**Comment by andy-maier** [comment]
This is a non-issue because "make install" needs to be invoked before "make develop", and if that is done, it works fine.

Also, this has been improved as of PR #100; "make develop" now invokes "make install" automatically if needed.
