### ISSUE TITLE
Should use-pull be persistent and part of a particular server

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#534]
Should this general option be part of a particular server or treated as a "transient" so that its really more part of an interactive session.  This came up because one user asked why they could not make a particular server in the server file as use-pull no permanently and also when I was tracking issue #530 I found that to be a logical concept.

**Comment by andy-maier** [comment]
Has been addressed in PR #533.

**Comment by KSchopmeyer** [comment]
We discussed this and and agreed that we should do it and it should be part of V 0.6.0
