### ISSUE TITLE
docs/pywbemcli/cmdshelp.rst uses current terminal width

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#542]
Each time this file is created it now uses the current terminal width and therefore the format changes since we allowed the width of --help to follow the terminal width.

While the variable width is logical for the user we need a way to make it standard when the cmdshelp.rst is created to avoid the continuous change.

**Comment by andy-maier** [comment]
At the moment, the correct terminal width to re-create the file in its current formatting is 78.

I agree that we should fix that by making the generation of that file independent of the terminal width.

Also, we should agree on a larger width we generate the file with.

**Comment by andy-maier** [comment]
PR #544 addresses this in master, but leaves the width still at 78.
