### ISSUE TITLE
Connection show output does not match pywbemcli known output-format types

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#572]
Connection show is a piece of work I did initially just for me in testing but survived.  It is a sort of text form:

name: mock1 (current)
  server: None
  default-namespace: root/cimv2
  user: None
  password: None
  timeout: 30
  verify: True
  certfile: None
  keyfile: None

That is neither table, nor CIM object but not really raw text. 

I propose to at least make a table option for this.

DISCUSSION: Should the table output be the only output or just when table is selected???

**Comment by andy-maier** [comment]
Addressed by PR #575.
