### ISSUE TITLE
Increase test coverage to 94%

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#577]
Version 0.7.0 is at 91.4%. Goal for 0.8.0 is to increase the test coverage to 94%.

**Comment by KSchopmeyer** [comment]
Currently the coverage is


Module | statements | missing | excluded | coverage
Total                3240 |        283 |             0 |         91%

It takes about 32 additional lines of code coverage for each 1% increase of coverage.  Therefore we have to pick up about
90 lines of coverage.

The major modules where we can pick up coverage are:

Module                                                                | statements | missing | excluded | coverage
pywbemtools/pywbemcli/pywbemcli.py              | 240              |         22 | 0 | 91%
pywbemtools/pywbemcli/_pywbem_server.py    | 219              |        24 | 0 | 89%
pywbemtools/pywbemcli/_association_shrub.py | 303             |        34 | 0 | 89%
pywbemtools/pywbemcli/_context_obj.py           | 150              |        34 | 0 | 77%
pywbemtools/pywbemcli/_common.py               | 677              | 77         | 0 | 89%

**Comment by andy-maier** [comment]
Shortly before releasing 0.8.0, its test coverage is at 90.7%.
Note that it dropped by 1.6% as of PR #764, for unknown reasons.
