### ISSUE TITLE
Location of the pywbem connections file

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#596]
Today the file is located in the current directory. 

There are several logical alternatives:

1. located in current directory
2. Located in users home directory
3. Search first current directory and then user home directory
4. New optional parameter to identify the source of the connection file.

NOTE: Since this file is not provided as configuration information with install either clone or PYPI there is no reason for an alternative to look for it in the OS base app configuration information directories.

 It is proposed that it be set into the users home directory.

Note that we want to coordinate this so that the repl history file and the connection file are not in completely independent and different locations.

**Comment by KSchopmeyer** [comment]
I chose the following algorithm.
Finding file:

1. try current directory.
2. If does not exist, try users home directory

Creating new file:

Creates only if no file can be found in current or home directory

Always creates new file in home directory.

**Comment by andy-maier** [comment]
Addressed in PR #659.
