### ISSUE TITLE
Expand use of documentation index

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#598]
The sphinx documentation includes an index.  While the index was well used by pywbem because the code documentation automatically was indexed, pywbemtools is less-well served because there is little code documentation so that the index entries must come from inclusion of the '.. index::' sphinx command in the documentation.

We should, at least create an index entry for every general option and for the command groups and commands.

Note: Definition of the .. index:: command is documented at: https://www.sphinx-doc.org/en/1.5/markup/misc.html under the title "Index-generating markup"

Since generating an index is an almost endless task, I suggest that we generate the general entries for major ideas, and the commands and options and then later we can see if more are needed.

**Comment by andy-maier** [comment]
Fixed in PR #599.

**Comment by KSchopmeyer** [comment]
Close ths one as complete.  We will not do any more specific effort to expand the index.  We are expected to review and possibly expand index entries as part of modifying documentation

Close
