### ISSUE TITLE
Handling passwords

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#6]
The initial code leaves the password logic ompletely open in that we simply take the password from a global option input and even allows saving it in an env varaible.  That is unacceptable so we need to sort out what we should do with passwords to allow either open passwords (i.e. for some test environments) and protected passwords when the user requires them.
Proposal:

1. Make inputting the password an option.  If the user wants to supply it with a global option, that is ok.  If, they want to, they can supply the user name but not the password and we will ask for the password.

**Comment by KSchopmeyer** [comment]
We can put this into a dot file in home so that at least it is restricted to this user and also base64 hash it.  Set to permissions 600

**Comment by andy-maier** [comment]
Addressed in PR #24.
