### ISSUE TITLE
Connection test cannot deal with server that does not include class operations

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#606]
The "connections test" command uses only EnumerateClassNames to test if a connection supports CIM/WBEM operations.  If a server does not support the class operations, this fails, even if the server were to support instance operations.

The command should be expanded to test for some instance operation if the class operations fail or to tread the class operation failure with a known CIMError as the existence of a server.

**Comment by andy-maier** [comment]
Addressed in PR #615.
