### ISSUE TITLE
Reorganize 'server profiles' and 'server centralinsts' commands

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#612]
Listing profile and central instances information does not belong more to the `server` command group than for example listing classes, instances or qualifiers. All are on a server, and none is specifically about the server itself.

The proposal is to move the `server profiles` and `server centralinsts` commands into a new command group `profile`:
* `profile list` - list the profiles on the server, with filter options by org/name. Like today's `server profiles`.
* `profile centralinsts` - list the central instances of the profiles on the server, with filter options by org/name. Like today's `server centralinsts`. TBD: Should we start naming specific profiles as positional parameters.

**Comment by andy-maier** [comment]
Decided to move this one beyond 0.7.0.

**Comment by KSchopmeyer** [comment]
See pr #676
