### ISSUE TITLE
Mark Python 2.7 and 3.4 support as deprecated

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#630]

**Comment by andy-maier** [comment]
DISCUSSION:
How should the deprecation be surfaced when using pywbemcli?

**Comment by KSchopmeyer** [comment]
1. We propose to do this as a warning on startup.

2. Lets create general deprecation mechanism similar to pywbem so we have tool for other deprecations.

**Comment by andy-maier** [comment]
Addressed in PR #651
