### ISSUE TITLE
Need an output option for displaying Value/Valuemap information

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#634]
I would like an option on output for displaying VALUE information instead of, or in addition to, VALUEMAP information. SNIA uses the Dedicated property on ComputerSystem. But you need to have a cheat sheet handy to tell you Dedicated="24" is a NAS Head, Dedicated="25" is a Self-contained NAS and Decidated="16" is a File Server. Similarly, you need a cheat sheet to tell you that HealthState="5" means "OK".
For demo's I can get the class to show the cheat sheet, but Dedicated has over 40 values. 24 and 25 are pretty much in the middle. Manually coordinating what a number corresponds to is not all that easy.

**Comment by andy-maier** [comment]
Great idea!
Clarifying that this applies to CIM instances only, and also that it makes sense only for table output formats.

**Comment by FarmerMike252** [comment]
Yes, it is desired for the display of instances. An doing this as part of the table format is fine.

**Comment by andy-maier** [comment]
PR #636 addresses this. Please try it out, and comment on the discussion points I listed there.
