### ISSUE TITLE
Issue with deprecated/removed mock methods/variables

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#642]
We have two items in pwbem_mock that are marked experimental and we are discussing whether to leave them or just remove them immediatly before the beta or final 1.0.0 release.  In any case, any use of these items (see pywbem issue #2284 will have to be cleaned up to account for the possible removal.

These items are:
* the `FakedWBEMConnection.compile_dmtf_schema()` method in favor of a new method `compile_dmtf_classes()`, and
* the `DMTFCIMSchema.schema_mof_file` property in favor of a new property `schema_pragma_file`.

**Comment by andy-maier** [comment]
On the two items:
* PR #643 updates the test code so that the only occurrence of using `compile_dmtf_schema()` is changed to use `compile_schema_classes()` if that method exists, and otherwise uses the old method.
* `schema_mof_file` is not used on pywbemtools.
