### ISSUE TITLE
Cleanup of PYWBEMCLI_* env variable definitions

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#658]
Currently this list of env varaible names is contained in Pywbem_server class because it was originally just the components of that object.  However, subsequently we have expanded the set of exports beyond this to include things like pdb, the connections file, etc. These are not part of pywbem_server.

We should consider making the envvars their own object and even refine that object to be able to provide more information such as help on the env variables, etc.

**Comment by KSchopmeyer** [comment]
NOTE: This is largely an internal task, something for us to make the code easier to handle..  The single user advantage of this that I can see is that if we did this clean so we produced a dict of env vars, corresponding general vars, description, it could be use as a means to generate help on env variables.

**Comment by andy-maier** [comment]
Agreed to move to 0.9.

**Comment by KSchopmeyer** [comment]
Close, will not do

**Comment by andy-maier** [comment]
Reopened this issue, since we are now introducing a second command in pywbemtools that can reuse some of the env vars, so it makes sense to move them to a neutral place.
