### ISSUE TITLE
pywbemcli help for --connections-file

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#660]
The general help outputs a help text that defines the default connections-file as the file name "pywbemcli_connection_definitions.yaml" in the users home directory.  What it should really output it the exact path name for that file.  This is trivial for linux  but can be a mess for windows to find the home directory.

However, the current test structure in test_generalopionts.py tests the full text of the help against the pywbemcli -h output.   If we were to insert the actual path of the default file, that messes up the current test.  Maybe it is time to change that test so it matches the others, testing portions of the help rather than the complete help. Then the help output could ignore that variable data.

Right now I set this one to 0.8.0

**DISCUSSION**

**Comment by andy-maier** [comment]
Adding the file path to the help text requires loosening the check for the expected help text, e.g. to check only for a few strings to be in, because the location changes from test system to test system.

**Comment by KSchopmeyer** [comment]
See pr #675
