### ISSUE TITLE
Directions and priorities for pywbemtools 0.8.0

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#667]
**Bug and issue status:**

* [Open bugs](https://github.com/pywbem/pywbemtools/issues?q=is%3Aissue+is%3Aopen+label%3A%22type%3A+bug%22)
* [Open issues for 0.8.0](https://github.com/pywbem/pywbemtools/issues?q=is%3Aissue+is%3Aopen+milestone%3A0.8.0)

**Release content of 0.8.0:**

These issues have a target release of 0.8.0.

* Bugs:
  * instance associators/references tests with wildcard keybindings fail(issue #458) - CLOSED
  * instance shrub misses associated instances when specifying host and namespace (issue #657) - CLOSED
  * Repeated unhandled exception in event loop, Python 2 (issue #224) - CLOSED

* Cleanup:
  * Enforce Pylint in CI runs to have no findings (issue #668) - DONE PR #706
  * Work down TODOs (issue #XXX) - **OPEN**
  * pywbemcli help for --connections-file (issue #660) - CLOSED

* Testing:
  * Code coverage: The 0.7.0 release has 91.4% coverage. Goal for 0.8.0 is to increase the coverage to 94% (issue #577) - **P1** PARTLY DONE
    - PR #693: Now between 92 and 93 percent
  * Change all tests to use pytest (issue #91) - DONE
  * Function testing of subcommand server only uses single namespace (issue #183) - **P1** - DONE
  * ordering of pick instancename functions (issue #459) - CLOSED

* Ease of use:
  * Allow unsetting of general options in interactive mode (issue #350) - DONE
  * Let order of properties in --propertylist determine prop order in instance table output (issue #702) - DONE

* Documentation:
  * Expand use of documentation index (issue #598) - PARTLY DONE
    **COMMENT: This is a continuing effort so should be part of every release)**

* Speed up mock load for large loads. (issue #689) **P1** - DONE
* Mock script interface to register dependent files (issue #748) - DONE

**Content beyond 0.8:**

These issues have no target release. This list may not include all [issues without release target](https://github.com/pywbem/pywbemtools/issues?q=is%3Aissue+is%3Aopen+no%3Amilestone)

* Other Functionality:
  * Package mock definitions into a single file (issue #674) **P1** 

* Cleanup:
  * Cleanup of PYWBEMCLI_* env variable definitions (issue #658)
  * Cannot pass WBEM URI with quotes through test stdin (issue #387)

* Testing:
  * Refactor the tests so that we run more tests in interactive mode. This would significantly increase the speed of running the tests (most of the time for each test is pywbemcli startup).

* Indications:  **QUESTION/KS: How important are indications and subscriptions to pywbemcli. I do not know**
  * Possible indication listener (run as background process or separate tool) (issue #430)
  * Subscription management (issue #4)

* Ease of use:
  * Invalid diagnostic information when connection file load fails (issue #661) - **P1**
  * Find means to show classes filtered by characteristics, part 2 (issue #447) - **P1**
  * Expand class tree to show superclasses and subclasses (issue #449)
  * Explore possible use of tab completion usage with options variables and more command arguments. Today we have implemented the ?  as a sort of artificial completion mechanism where these wildcards trigger some sort of lookup and present a list of possible results.  Thus INSTANCENAME has a lookup if the keybindings is simply the "?" wildcard. Could we consider extending these to a) use tab completion in place of wildcard lookup (note that it would have to work in both command line and interactive cli modes) b) use the wildcard completion on more options (issue #482)
  **NOTE**: The click project is progressing with completely redefining the auto-completion functionality (see click issue #1484 and a corresponding pr in progress). This means that we should take this work into account in defining what we want to accomplish and how to accomplish it for auto-completion.
  * Use the wild card concept now used on INSTANCENAME for the value component of other options and arguments: 
    * server profiles and server centralinsts.
    * --namespace option
    * --name general argument to get name of persistent connection
  * Add capability to include a comment for connection definitions in connections file (issue #761)

* Output formats:
  * Add a table format for classes. Currently we can only display classes as MOF, REPR, XML.  (issue #249) - P2
  * Add JSON as output format (issue #184) - Prio 1
  * Add Latex format (issue #185)  **COMMENT/KS. Does latex really matter unless we get it for free with some tool?**
    * Class tables.However Karl has not come up with a logical table equivalent to date.  SUGGESTION:  Look at Jim's and Karl's existing table displays and try to sort out how you handle things like overrides, qualifiers, etc.
  * Consider a machine-readable form of output that would allow command redirection at least at the shell level. Note that click itself does not really support the idea of redirection in the interactive mode (output of one command available as input to the next command) but we could use the click context as a way to pass results to input in the interactive mode (Which would make the command mode different than the interactive mode). Some examples of usage might be: Run a command to get the namespaces and then run anther command on all of those namespaces.The easiest idea for this is the processing of things like connection names, instancenames, classnames, and namespace names. or lists of the same.

* Maintaining server state in interactive mode:
  * Consider maintaining some information between commands in the interactive mode beyond what is maintained by the Server class. Remember that profiles and namespaces are maintained in the Server class instance as long as that object exists.  ex. classes by namespace. Thus we would extend our pywbem_server to allow it to maintain more information. The information could include at least class names by namespace (issue #483)
  * In the interactive mode consider maintaining connection information in memory when different connections are selected so that if a server was selected, any previous current connection would not be completely cleaned (today we clean each connection as it is selected).  Some ideas are stash of class names or classes by namespace.  Maintain the concept of a current thing; current class, current instance that would be applied to commands (issue #484)

* Profiles:
   * Expand the centralinsts cmd to use the shrub to display information on that central instance (issue #481)

* Other ideas:
  * Support getting operation statistics from the server (this was implemented in at least pegasus and j server) (issue #588)
  * Extend pywbemcli so that plugins representing new commands and groups could be added by users (issue #587)
  * Specify property type in instance create to avoid class lookup (issue #187)
  * Support embedded instances as input (issue #589)
  * Analyze SBLIM's wbemcli against pywbemcli (issue #451)

**Comment by KSchopmeyer** [comment]
I made some specific comments above but in general, I think we should define a specific set of goals for 0.8.0 that we feel are important to users and use those as the drivers for each release.  I think each version should have at least one key goal that means something to the user, not just to us developers.  Typically this is a new or significantly changed piece of functionality which is what sells to users.

Thus, I need to poll at least a couple of users. ACTION KS_

Thus each release always does:

1. Imporove or at least mainain coverage.
2. some specific things we need to do for better development, testing, etc. (ex. refactor tests to use make them faster)
3. Work to keep pylint down.
4. Additions from users as required or desired.
5. At least one issue that is driven by users ( new functionality, improved usage, etc.) and should be important  and visible to them(reason why they want to upgrade)
6. Others functional improvements that we have thought out. We often see the tool better than the users do so we see new functionality, usage, documentation better than they might so we should incorporate our  new ideas. But these are not the drivers, it is the user requests that drive each release.

Finally, I propose that we try to limit the number of new things for each release and turn around releases more rapidly; smaller but more increments.
