### ISSUE TITLE
Define the cmd line options into groups for the help output

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#672]
We had discussed grouping command line options earlier in the development process sot that they were organized within groups in the help display.  However, click did not offer that capability (Note: that this exists in argparse). About 6 months ago a new click contrib (click-group-options) was added to the click contrib project and that package now appears to be stable so the capability to group the command line argumetns exists for us.

This click contrib library works by installing the click-option-group package and causes no other internal changes to pywbemcli beyond changing he decorartors on the option definitions to break them into groups.

The issue for us is what is a logical  set of groupings that aids our users.

**Comment by KSchopmeyer** [comment]
The following is a first attempt, just to establish that this works.

**Comment by KSchopmeyer** [comment]
NOTE: This code works by adding two new decorators:

@optgroup.group('Server definition',
                help='The alternatives for defining a server')
@optgroup.option('-n', '--name', 'connection_name', type=str, metavar='NAME',

In addition it allows defining a group with characteristics, like (require one, require all, mutually exclusive, etc as an option by using subclasses of the base optgroup class.

**Comment by KSchopmeyer** [comment]
We agreed that we will:

1. Remove the pull group as separate group and put in general options.
2. change the pywbemcli configuration to general options
3. Expand wording of the descriiptions
4. Determine what additional tests we need to assure that options that do not apply from server category for example (mock) are flagged.
5. Assure that the override (ex. user with -n name works.)

**Comment by KSchopmeyer** [comment]
I overlooked the fact that this click contribution only supports python 3.6 and above, at least partly because its setup.py uses pathlib package which only supports python 3.6 and above.   Writing pr to see if we can get them to expand support to match click.

**Comment by KSchopmeyer** [comment]
The author is willing to consider providing compatibility back to python 3.5 or maybe 3.4 if someone else does the work but clearly stated that he will not consider compatibility with python 2.7.

At this point the initial problem with python 3.5 is the use of the use of PathLib in the setup.py.  We have not explored further.

I note also that the author later pretty much said he is not interested in python 3.5 compatibility, contermanding his earlier interest if I did the conversion.

**Comment by KSchopmeyer** [comment]
There is another much more limited stand-alone library that would provide the segregation of options into groups but it is not part of the click-contrib https://github.com/janLuke/cloup/blob/master/cloup/_cloup.py  which accomplishes grouping but no semantic control (exclusions, etc.)

Note that there is also a very old issue in click that discussed both of the current public implementations : https://github.com/pallets/click/issues/373

**Comment by andy-maier** [comment]
Since the click-option-group package only supports Python 3.6 and above, we would either have to spend the effort to backport the function to Python 3.4 and 3.5, and we would not get it into Python 2.7. I don't think this functionality is worth it to drop support for Python 2.7, or to spend the effort to backport it to Python 3.4 and 3.5.

As a result, the only option seems to be to defer this functionality until we drop these versions for other reasons.

**Comment by KSchopmeyer** [comment]
There is one alternative, a very simple proposal that would gain the grouping of the top level group but not the other features such as choice exclusion.

**Comment by KSchopmeyer** [comment]
After a review of the code in click_ tontrib option groups it is vclear that it is comppletly committed to python 3.6 + since it include all of the type hinting that started with that version.

It is a clean model in that it uses decorators for both the group and grouped option definitions:

        @optgroup('Group 1', help='option group 1')
        @optgroup.option('--foo')
        @optgroup.option('--bar')
        @optgroup.group('Group 2', help='option group 2')
        @optgroup.option('--spam')

Doing the grouping with decorators creates a complex set of code for what should be a simple problem.

Some alternate syntaxes might be something simpler like:

```

@click.command()
@click.option_group('Output options:', [
    click.option('--verbose'),
    click.option('--output')
])

or

```
@cli.command(cls=CustomCommand)
@click.option('--option1', cls=CustomOption, help_group="Group1")
@click.option('--option2', cls=CustomOption, help_group="Group2")
@click.option('--option3', cls=CustomOption, help_group="Group1")
def mycmnd(option1):
    pass

or even

```
@click.command()
@click.argument('path')
@click.section('Section A', [
    click.option('--a1'),
    click.option('--a2')
])
@click.section('Section B', [
    click.option('--b1'),
    click.option('--b2')
])
def cli(path, a1, a2, b1, b2):
    pass

**Comment by janLuke** [comment]
> There is another much more limited stand-alone library that would provide the segregation of options into groups but it is not part of the click-contrib https://github.com/janLuke/cloup/blob/master/cloup/_cloup.py which accomplishes grouping but no semantic control (exclusions, etc.)
> 
> Note that there is also a very old issue in click that discussed both of the current public implementations : [pallets/click#373](https://github.com/pallets/click/issues/373)

I'm the author of cloup. I'm considering adding constraints to cloup and I ended up here (don't ask me how or why). 

Adding constraints to cloup would be very simple and I actually wrote a draft months ago (in a local branch). In my current design, you can pass one or multiple constraints to an `OptionGroup`:

```python
@option_group(
    "The option group name",
    "This is a long description of the option group.",
    option('-o', '--one', help='1st input option'),
    option('--two', help='2nd input option'),
    option('--three', help='3rd input option'),
    constraints=[MutuallyExclusive()]
)

# there are "shortcuts" for the predefined constraints:
@mutually_exclusive_group(
    "The option group name",
    "This is a long description of the option group.",
    option('-o', '--one', help='1st input option'),
    option('--two', help='2nd input option'),
    option('--three', help='3rd input option'),
)
```

The base class for constraints:
```python
class OptionGroupConstraint(abc.ABC):
    @property
    @abc.abstractmethod
    def help(self) -> str:
        pass

    def check_consistency(self, group: OptionGroup):
        """
        Raises InconsistentOptionGroup if the contained options cannot satisfy
        this constraint independently from the user input (it catches your mistakes). 
        For example, MutuallyExclusive() cannot be satisfied if multiple options 
        in group are required.

        :param group: an OptionGroup
        :raises InconsistentOptionGroup: if
        """
        pass

    @abc.abstractmethod
    def check(self, options: List[click.Option], values: Dict[str, Any]):
        """
        Checks the constraint against the parsing result.
        :param options: list of Option objects
        :param values: map {option_name: value}
        :raises click.exception.UsageError: if the constraint is violated
        """
        pass
```

Would this be useful for you? What constraints would you be interested in?
