### ISSUE TITLE
pywbem cli test loses the default connections file

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#680]
There is an issue in the test mechanism that backs up and restores the default connection file such that the yaml file can be lost during tests.  The expected behavior is that the file and its backup are saved at the beginning of each test session and restored
at the end of the session but we have noticed the yaml file gone.

**Comment by KSchopmeyer** [comment]
See pr #681

**Comment by andy-maier** [comment]
Addressed by PR #681 for master and PR #685 for 0.7.1.
