### ISSUE TITLE
Add more Qualifier filters

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#682]
The following qualifiers are proposed
1.    --schema={schema}, maybe --no-schema={schema}, maybe --classname={classname-pattern}

2.    --superclass={classname-pattern}, --no-superclass
    Consider separating direct superclass from general inheritance.

**Comment by KSchopmeyer** [comment]
We discussed the concept of using something line enumerate classes with the filters as part of a chain of commands where the output would be the list of classnames that could be used for other commands.

Currently, click would only conceptually support this from the command line using the stdin to present the list and beyond that, there is no support.  Further in the interctive mode there is no support for redirection with an interactive session directly from one command to the general case of other commands despite the fact that click has command chaining.

**Comment by andy-maier** [comment]
Define scope for 0.9.0

**Comment by andy-maier** [comment]
We decided to do both schema and superclass

**Comment by KSchopmeyer** [comment]
1. --schema={schema}, maybe --no-schema={schema}, maybe --classname={classname-pattern}
On reflection I can find absolutely no use of schema qualifier in the DMTF schemas so I wonder if this is really useful.
**DISCUSSION**


I suggest the following alteration to the syntax for item to filter by superclasses

2.    --superclass={classname-pattern}, --no-superclass
    Consider separating direct superclass from general inheritance. 

change to:
--superclass={classname=glob-pattern, None} where None is the equivalent of the --no-superclass above.

Consider separating direct superclass from general inheritance. The idea here would be to either lglob for the direct superclass or for the glob anywhere in the general list of superclasses. This can be handled by a) further complicating the option value with something that indicates that it for mutliple superclasses TODOP:Not sure of exact fomr b) creating a second option --superclasses

3. We might also consider the qualifiers for EmbeddedObject and EmbeddedInstance.

4. After a review of all of the qualifier declarations, I am not finding many more that would really be useful except possibly Abstract

**Comment by KSchopmeyer** [comment]
Discussion.  for the version lets only support the case of version greater than <version>. Make the name "since" <version> to make it clear what we are asking for.

**Comment by KSchopmeyer** [comment]
Lets try using the syntax "subclass of" to clarify that this is a subclass (direct or indirect) of the named class.
