### ISSUE TITLE
I am getting a Windows error (WinError 995) on a number of pywbemcli commands

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#690]
I am getting the WinError 995 error on some of my pywbemcli commands. The command produces the expected output but then I get the following error message:

Unhandled exception in event loop:
  File "c:\users\farmermike\appdata\local\programs\python\python38-32\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "c:\users\farmermike\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\farmermike\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)

Exception [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
Press ENTER to continue...

I press enter and can continue with my script, so this is not a high priority, but it would nice to get rid of the error message.

**Comment by andy-maier** [comment]
This seems to be the error reported here: https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1023#issue-534396318. They have opened a Python bug against 3.8, which changed the type of event processor to async. The prompt-toolkit issue suggests that changing the type of event processor back may address the issue.

The 'blessed' project also encountered this (issue https://github.com/jquast/blessed/issues/121) and they relate it to using prompt-toolkit>=3.0.

I think we should first try to pin prompt-toolkit to <3.0.

**Comment by andy-maier** [comment]
@FarmerMike252 Mike, I have a PR #696 that I think fixes this, but it requires your confirmation. Could you please verify that the error is gone when using pywbemcli from the branch of that PR?

**Comment by FarmerMike252** [comment]
I have run two of my CLI scripts, including the one that had errors in yesterday's SM Lab meeting. Both scripts ran clean. So, I believe the problem is successfully fixed.

**Comment by FarmerMike252** [comment]
Ooops! I didn't realize I was not supposed to close the issue.

**Comment by andy-maier** [comment]
NP, Mike. Thanks for testing it! I'll roll back the PR to 0.7.1 then and we'll discuss releasing it in our call today.
