### ISSUE TITLE
Remove changes required by click-repl to make all help= strings unicode

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#691]
Because of an issue in click_repl (see Issue https://github.com/click-contrib/click-repl/issues/71 filed on click_repl and our issue #224 (Closed) we are required to make all help strings in options unicode.

I am opening this issue so that we can remvoe that requirement when click_repl fixes the issue documented on their site or we find a better workaround than making all help strings unicode or we drop support for python 2.7.

We will not assign a Milestone to this because the code now works with prompt-toolkit 2 so that the fix will only mean that we can remove the limitation on the help strings.

NOTE: However, it appears that the next version of prompt-toolkit will not even support python 2.

**DISCUSSION:** Close because this issue has been bypassed by changes eliminating py 2.7 and the unicode designations on help attributes have been dropped.

**Comment by andy-maier** [comment]
Reclassified this as cleanup, because the earlier bug had already been addressed by changing all help test to Unicode.

**Comment by andy-maier** [comment]
**DISCUSSION**: What is left for this issue?

**Comment by KSchopmeyer** [comment]
This is just a reminder for the future if the dependent layers fix the problem with requiring unicode strings or we go to python 3 only

**Comment by andy-maier** [comment]
This PR is waiting for the dependent layers fix the problem with requiring unicode strings or for us dropping Python 2.7 support.

**Comment by KSchopmeyer** [comment]
**DISCUSSION**: I believe that this issue should be closed because it is no longer relevant and our help string definitions have already be modified to remove the unicode designation as part of the upgrade to set the minimimum version to 3.8

**Comment by andy-maier** [comment]
This issue is no longer needed because it was actually done as part of removing Pyhton 2.7 support.
