### ISSUE TITLE
general options pull-max-count not reported anywhere

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#694]
This general option is not being reported in the show command because it is not kept in the pywbem_server class. We consider it to be not server specific.  

The end result is that it shows up nowhere in reports the user can see.

**DISCUSSION**

**Comment by andy-maier** [comment]
I think we can make it part of a connection, for both types (server / mock).

**Comment by KSchopmeyer** [comment]
We agreed to move this variable back into the pywbemcli_server class and make it persistent.
