### ISSUE TITLE
Versioning of the code since it will have multiple tool components

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#7]
Right now the `__version__` component is in pywbemcli directory.   We probably need to create a wbemtools directory so that we have a common basis for anything that requires commonality betwen tools.  Right now, that is probably only the `_version.py` definition.

**DISCUSSION:** Alternatives?

**Comment by KSchopmeyer** [comment]
ISSUE: This should not exist any more.  pbr should be the source for the version.

Karl will change.

**Comment by KSchopmeyer** [comment]
I agree with Andy's comments  Further, we proposed a change to the overall directory structure to that there is a single top level directory pywbemtools and under that the specific module and other directories. Thus, pywbemcli would become a subdirectory of pywbemtools.

**Comment by KSchopmeyer** [comment]
We propose to make the basic change before we release 0.5.0

**Comment by andy-maier** [comment]
We discussed this today and decided to do this not in 0.5.0.

**Comment by andy-maier** [comment]
When using `pbr`, the version is determined from the git tags, so there is a common version for the whole project. If we continue to use `pbr`, this is a non-issue. But see #178 which proposes to drop the use of `pbr`.

**Comment by KSchopmeyer** [comment]
Close this as don't fix.  See #178 where any discussion/changes will occur

**Comment by andy-maier** [comment]
Will be pursued in issue #178.
