### ISSUE TITLE
Output format of shrub changes between 0.17 1.0.0 B1

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#704]
The format of the instancename display of the shrub changes between version 0.17 and 1.0.0 B1 in that in the old version the output instancename is proceeded by /: but tje first component is the class name when pywbem 1.0.0b1 is used.

I marked this as rollback needed but that is just an option today.  This is not the type of error the user will notice.  However, it breaks our tests with pywbem 1.0.0 so we need to fix it ASAL

Pywbem 0.17.1

```
    'Role       AssocClass    ResultRole    ResultClass    Assoc Inst paths',
    'Initiator  TST_A3        Target        TST_EP         /:TST_EP.InstanceID=2(refinst:0)',  # noqa E501

```
Pywqbem 1.0.0 b1

    'Role       AssocClass    ResultRole    ResultClass    Assoc Inst paths',
    'Initiator  TST_A3        Target        TST_EP         TST_EP.InstanceID=2(refinst:0)',  # noqa E501

**Comment by andy-maier** [comment]
I don't think this needs to be rolled back into 0.7.

**Comment by andy-maier** [comment]
We agreed not to roll it back.
