### ISSUE TITLE
Change base file name of connections file

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#716]
The base file name of the connections file is currently: `pywbemcli_connection_definitions.yaml`.

That has two issues:
* It is not a hidden file, even though it is basically an internal file that is not normally supposed to be edited by the user.
* Its file name is no longer consistent with the rest of the documentation about the connections file, which uses the term "connections file".

Proposal:
* Change the base file name to `.pywbemcli_connections.yaml`.

That is consistent with the file name of the history file in the user's home directory: `.pywbemcli_history`

**DISCUSSION**

**Comment by KSchopmeyer** [comment]
Karl agrees.
