### ISSUE TITLE
Disable warnings in interactive mode

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#723]
Karl's ppp script showed warnings in interactive mode. For example:
```
$ ppp -n mock1 -T
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli> class enumerate --no
-/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/nocasedict/_nocasedict.py:278: UserWarning: Before Python 3.7, initializing or updating a NocaseDict object from a dict object is not guaranteed to preserve the order of its items
  self.update(*args, **kwargs)
CIM_Foo
```

However, I was not able to reproduce this with just pywbemcli.

DISCUSSION: Can this be reproduced with just pywbemcli?

In any case, we should ensure that pywbemcli in interactive mode does not show any Python warnings.

**Update:** I was using python 3.8 by mistake when I tried reproducing it, but that one has ordered dicts by default so it does not issue the UserWarning. With Python 2.7, the userWarning can be reproduced with just pywbemcli:

```
$ pywbemcli -n assoc
pywbemcli> class tree                                                                                                       
Deprecation: Pywbemcli support for Python 2.7 is deprecated and will be removed in a future version
-/Users/maiera/virtualenvs/pywbemtools27/lib/python2.7/site-packages/nocasedict/_nocasedict.py:278: UserWarning: Before Python 3.7, initializing or updating a NocaseDict object from a dict object is not guaranteed to preserve the order of its items
  self.update(*args, **kwargs)
root
. . .
```

**Comment by KSchopmeyer** [comment]
Remember that I am using an python 3.6.7.  However, I tend to agree that the easiest mode for the user is default == disabled.  Otherwise with some python versions you are always setting the warnings didabled flag.

**Comment by andy-maier** [comment]
Analysis of current warnings in pywbemcli and packages it uses:

* `deprecation_warning()` function in pywbemcli, controlled by `--deprecation-warnings` general option:
  - used for Python version deprecation warning.

* Python warnings, controlled by PYTHONWARNINGS env var:
  - `warnings.UserWarning`
  - `warnings.DeprecationWarning`
  - `pywbem.ToleratedServerIssueWarning`
  - No Python warnings known from other packages

**DISCUSSION:** Discuss which of these warnings we want to control in which way.

**Comment by andy-maier** [comment]
We discussed this and agreed to the following:
1. We turn the deprecation_warning() function into a proper Python warning.
2. We support an option `--warnings` and `--no-warnings` that controls all Python warnings, with default False, where False means we don't do anything (and the PYTHONWARNINGS env var controls it) and True means we show all warnings.
