### ISSUE TITLE
Add punits to property names for table output of instances

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#727]
It has been requested that it would be useful to users if the punits qualfier were used (where it exists) to futher document instance table output.

Note that the punits is a machine readable format and we would have to change that to human readable.

Finally, would it be logical to also consider some additional formatting of data, for example very large integers to be comma separated.  So 123456 would be 123,456. Note: the comma is region specific so this idea may not be worthwhile.  We concluded because of the confusion this can cause we will ignore it

**Comment by andy-maier** [comment]
That's why it was created :-)

**Comment by andy-maier** [comment]
We agreed on the following:
- Use PUnit if present
- Use Units as a fallback
In both cases, transform the unit names into SI unit names, and the multipliers into SI prefixes as far as possible so that remaining multipliers are >1

**Comment by andy-maier** [comment]
I have opened https://github.com/pywbem/pywbem/issues/2423 to implement the support in pywbem.

**Comment by andy-maier** [comment]
PR https://github.com/pywbem/pywbem/pull/2424 adds support for translating PUnits and Units qualifiers to SI units.

**Comment by andy-maier** [comment]
Karl and I decided to put PR pywbem/pywbem#2424 into pywbem 1.1.0, and to release that with only a small subset of the currently planned content, and therefore soon.
