### ISSUE TITLE
Confusion between adding general params and connection show

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#732]
There is confusion within pywbemcli between modifying the general options for server parameters and the show command.

Thus with an existing connection tst1:

```
$ pywbemcli -n tst1
pywbemcli: --user blah --password blah connection show
```
... Shows the original values of --user and --password

However:

```
$ pywbemcli -n tst1
pywbemcli: --user blah --password blah connection select tst1
pywbemcli: connection show
```
... Shows the new values

This causes problems with one of the tests in test_general_options.py and that one uses stdin to process the multiple inputs. We disabled that test with PR #730 until this issues is sorted out.

**Comment by andy-maier** [comment]
I think the whole logic in `connection show` needs to be revisited. See also my comments on PR #733.

**Comment by KSchopmeyer** [comment]
Note line 568 in _cmd_connections.  The connection is reloaded from the connections file even if it is the current connection.

**Comment by andy-maier** [comment]
I tried the two cases described above with PR #743 and the result is (for a mock connection "simple"):

```
$ pywbemcli -n simple
pywbemcli> --user blah --password blah connection show
Connection status:
name               value  (state)
-----------------  ------------------------------------------
name               simple (current)
server
default-namespace  root/cimv2
user               blah
password           ******
timeout            30
use-pull
pull-max-cnt
verify             True
certfile
keyfile
mock-server        tests/unit/simple_mock_model.mof
                   tests/unit/simple_mock_invokemethod_v1s.py
ca-certs
```
... Shows the values of --user and --password that are specified for the show command

However:

```
$ pywbemcli -n simple
pywbemcli> --user blah --password blah connection select simple
"simple" current
pywbemcli> connection show
Connection status:
name               value  (state)
-----------------  ------------------------------------------
name               simple (current)
server
default-namespace  root/cimv2
user
password
timeout            30
use-pull
pull-max-cnt
verify             True
certfile
keyfile
mock-server        tests/unit/simple_mock_model.mof
                   tests/unit/simple_mock_invokemethod_v1s.py
ca-certs
```
... Shows the values of --user and --password from the connections file.

I think this is what one should expect, so I think the PR does not only do a cleanup but also addresses the original issue.

I have linked it with the PR so it will be closed when merging the PR.
