### ISSUE TITLE
Add missing dependency to nocasedict

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#754]
Should we also move to using the released version of NocaseDict before release of 0.8.0

**Comment by andy-maier** [comment]
Before PR #755, pywbemtools had no direct dependency on nocasedict, and pywbem does use a released version of nocasedict.

What I missed when reviewing PR #755 was that it should have added the dependency to nocasedict. I have just merged it (before I noticed it), so let's fix that as part of this PR.

This PR should add the same dependency as pywbem, i.e. `nocasedict>=0.5.0`.

**Comment by andy-maier** [comment]
PR #757 fixes this issue by adding the missing dependency.
