### ISSUE TITLE
Failure in tests from test_pywbemcli_operations because of urllib3 issue

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#811]
tests fail because of issue in urllib3 issuing deprecation warning from urllib3 and documented in pywbem issue # https://github.com/pywbem/pywbem/issues/2531.  This stops the tests.

As a temporary measure until a  pywbem 1.1.3 is released we prpose to simply disable the warning for this test.

**Comment by andy-maier** [comment]
This is done in PR #808 as part of the migration to GitHub Actions.

**Comment by KSchopmeyer** [comment]
This was fixed in pywbem 1.1.3 and can now be closed
