### ISSUE TITLE
Limit click version to < 8 vs dropping support for python 2.7

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#816]
Click has just announced an early alpha for 8.0. One of the features is removing support for python 2 and 3.5.  At the same time this announces support for a much redesigned shell completion environment. Thus we have a condrom.  If we want to gain use of the new completion environment, we lose support for python 2.

Discussion:

Drop python 2.7, and put off the use of the autocomplete that will be in click 8.0.  We can implement a simpler but limited subset with click-contrib autocomplete but that is a dead end since it is largely incompatible with future click.  If we tried to limit click to < 8.0 only for python 2.7, we really could not use the features since they will involve our code changes and real function differences between python 2.7 and 3.6+

Note that this does not affect pywbem, just pywbemcli.

A move like removing python 2.7 compatibility should be a major version change Although we should probably determine when we want to get on that train, The only solution I can see is:

1. Limit requirements.txt to < python 8.0 until we do a pywbem cli 1.0

2. Try to create a limited autocomplete functionality using the clickcontrib autocomplete module 

Andy proposes that we simply pin click 8 to to python 3.6 and + and determine if that is workable.  Also we can try to do the autocomplete if this does not mean extensive code.

**Comment by KSchopmeyer** [comment]
Note that moving to click 8.0 will involve more than just click itself as w use multiple click contribs such as click_spinner and click-repl.  In particular, we note that click-repl is currently incompatible with the current alpha release of click.

  File "/home/kschopmeyer/virtualenvs/pycli3/lib/python3.6/site-packages/click_repl/__init__.py", line 6, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'
Makefile:462: recipe for target 'install_py3.6.done' failed

**Comment by andy-maier** [comment]
Based on our discussion, we should pin click to <8.0 not just for the Python 2.7 reason, but also for the click_repl compatibility reason.
