### ISSUE TITLE
Support deletion of non-empty namespaces

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#885]
The new `namespace delete` command errors out if the target namespace is not empty. It would be good to have a simple way to get rid of a namespace. One option would be to add a `--force` or `--including-content` option to `namespace delete` which would delete the objects in the namespace as well.

**DISCUSSION (RESOLVED):**
* When deleting instances in the namespace, is that done with DeleteInstance so that instance providers get control?
* Do instances need to be deleted in a particular order?
* Does the command immediately error out at the point an object cannot be deleted?

**Comment by KSchopmeyer** [comment]
1. If delete namespace uses delete class, that has a — force option.
2. I can see wher we have to think out issues here. 1. Should associations be deleted first? 2. What about classes that support providers?  Class and no deletion are useful but clearly not production tools, ever. 

3. I think that there. Is a risk in some environments of errors but I would think that since this not a production use capability, we have to live with deleting what is possible and user lives with result.
4. Should we just disallow deleting interop namespace?

**Comment by KSchopmeyer** [comment]
Discussion:

1. Use of --force option.  Should we make it fail or successful completion?  Should we use the work force or is there a better word for what we are trying.  Lets change the wording to --include-instances for remove class and --remove-objects for for the delete namespace.
2.

**Comment by andy-maier** [comment]
Before implementing it, I try to summarize the design:
* We will continue to reject the deletion of an Interop namespace.
* The option for enabling the deletion of objects in the namespace in 'namespace delete' will be '--include-objects'.
* For consistency, we will add an option '--include-instances' to the 'class delete' command and deprecate its '--force' option'.
* When deleting objects in a 'namespace delete' command, the algorithm will be:
  * Determine all top-level classes via EnumerateClasses(classname=None, DeepInheritance=False, IncludeQualifiers=True).
  * Based on the Association qualifier, divide the top-level classes in associations, indications and ordinary classes, in order to delete them in the correct order.
  * For each top-level indication class, perform the internal equivalent of 'class delete --force'.
  * For each top-level association class, perform the internal equivalent of 'class delete --force'. We assume that cross-namespace associations will be handled correctly by not leaving a dangling half-instance in the other namespace(s).
  * For each top-level ordinary class, perform the internal equivalent of 'class delete --force'.

**Comment by andy-maier** [comment]
After initial discussion, it seems the direction is to go with ordering the dependencies in a topology sort when deleting a namespace, and to continue scoping the force flag when deleting a class to just the instances, but to add code checking for the dependencies that are so far ignored.

The design would then be:

* The option for enabling the deletion of instances of a class in 'class delete' will be renamed to '--include-instances', and the '--force' option will do the same but will be deprecated.

* We add a check to 'class delete' for the dependencies that were ignored so far, based on a dependency list of all classes in the target namespace (see below for details).

* We will continue to reject the deletion of an Interop namespace.

* The option for enabling the deletion of objects in the namespace in 'namespace delete' will be '--include-objects'.

* When deleting the objects in a namespace, the classes will be brought into a no-forward-dependency order by performing a topology sort on a dependency list of all classes in the target namespace. The dependencies cover:

  * inheritance
  * references (props+parms)
  * EmbeddedInstance qualifier (props, parms, return) (looking at the classes is sufficient)
  * EmbeddedObject qualifier on props (requires looking at the instances to get the embedded class or the creation class of the embedded instance)

  What is not covered is an EmbeddedObject qualifier on parms or return since the parm/return value is not available. If the topology sort detects cyclic dependencies, we retry with a dependency list that covers only inheritance and references. If the topology sort on that retry detects cyclic dependencies, we abort (the CIM Schema has no such cycles).
  
  We will then delete all instances in that no-forward-dependency class order, then all classes in that order, then all qualifiers.

* Since both the class deletion with instances and the namespace deletion with objects needs a dependency list of all classes, there is potential for a common function.

**Comment by andy-maier** [comment]
We discussed the design and it looks good enough to start with.
We would like to have the additional safeguard for 'namespace delete' with '--include-instances'.

**Comment by andy-maier** [comment]
Reopening the issue, since there are multiple PRs needed to cover it.

**Comment by andy-maier** [comment]
All PRs to address ths issue havwe now been created: #909, #910, #913
