### ISSUE TITLE
Add compile mof command to pywbemcli

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#886]
Add a command that would compile mof as a new pywbemcli command.

The options should probably be:

1. dry_run (syntax check only) -d/--dry-run  (Note that pegasus compiler calls this syntax check but we are doing more than syntax checking, we are also validating that compile can occur in the server environment). **NOTE/QUESTION:** I have one question for myself.  If we do dry run and a dependent is required are we protected against the compiler installing that prerequisite. I do not know today).
2. namespace  -n/--namespace (Optional to compile into other than default namespace). the --namespace general option also honored
3. Include dir: -I/--include \<dir\>  Can be specified multiple times

for example

pywbemcli -s http://local server compile blah.mof --namepace root/test --dry-run -include

questions:

1. Which group should it be in? Server, Connection?  Agree it should be server.
2. Should it allow compiling strings and files or just files?
3. Should it include a removal option (i.e. remove the things compiled by the target string/file similiar to mof_compiler?

Removal should be there.

Consider two separate commands:

Some of the possible name combinations are:
1. compile/uncompile
2. update-mof/remove-mof
3. compile-mof/remove-mof
4. add-mof/remove-mof **** This is the one we will use

**Comment by andy-maier** [comment]
We discussed the command names and settled on:
* `add-mof`
* `remove-mof`
