### ISSUE TITLE
add-mof and remove-mof issues after pr committed

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#896]
I found what appear to be two issues iwith add-mof and remove-mof when I tried to merge them into another pr.

1. The tests for remove mof expect the namespace to be part of the removed mof in the expected results but not in the returned mof.
2. 
**NOTE:** This item(1.) was  something in the local virtual environment. Moving to a new virtual environment cleaned up the tests that were returning remove-mof 'Deleting class ...' and 'Deleting instance ... ' messages with the namespace missing.

```
Example:
E                       AssertionError: Missing ws-agnostic in-string on stdout in test:
E                       Verify server command remove-mof of same mock file with --verbose via stdin
E                       Expected ws-agnostic in-string in any line:
E                       ------------
E                       Deleting instance root/cimv2:CIM_Foo.InstanceID="CIM_Foo1"
E                       ------------
E                       Actual output line(s):
E                       ------------
E                       Connection repository with 0 connection definitions and connections file "/home/kschopmeyer/.pywbemcli_connections.yaml" (does not exist)
E                       Mock environment for connection definition 'not-saved' will be built because no connections file is known.
E                       Generating LALR tables
E                       Compiling MOF from standard input into cache
E                       Deleting CIM objects found in MOF...
E                       Deleting instance CIM_Foo_sub_sub.InstanceID="CIM_Foo_sub_sub3"
E                       Deleting instance CIM_Foo_sub_sub.InstanceID="CIM_Foo_sub_sub2"
E                       Deleting instance CIM_Foo_sub_sub.InstanceID="CIM_Foo_sub_sub1"
E                       Deleting instance CIM_Foo_sub.InstanceID="CIM_Foo_sub4"
E                       Deleting instance CIM_Foo_sub.InstanceID="CIM_Foo_sub3"
E                       Deleting instance CIM_Foo_sub.InstanceID="CIM_Foo_sub2"
E                       Deleting instance CIM_Foo_sub.InstanceID="CIM_Foo_sub1"
E                       Deleting instance CIM_Foo.InstanceID="CIM_Foo31"
E                       Deleting instance CIM_Foo.InstanceID="CIM_Foo30"
E                       Deleting instance CIM_Foo.InstanceID="CIM_Foo3"
E                       Deleting instance CIM_Foo.InstanceID="CIM_Foo2"
E                       Deleting instance CIM_Foo.InstanceID="CIM_Foo1"
E                       Deleting class None:'CIM_Foo_sub2'
E                       Deleting class None:'CIM_Foo_sub_sub'
E                       Deleting class None:'CIM_Foo_sub'
E                       Deleting class None:'CIM_Foo'

```

2. The first line of the help (short help) is longer than a single line which is what we try to eliminate.  This causes the individual tests to fail on my local system with 80 col termina**l but mostly it means incomplete text in the group help (server -h)  where the short help ends with ... for these two commands.**

All short help messages should be displayable on a single line in a typical 80 column terminal without the ... at the end of the line meaning that click had cut off some of the short help as show below:

```
Commands:
  namespaces  List the namespaces of the server (deprecated).
  interop     Get the Interop namespace of the server (deprecated).
  brand       Get the brand of the server.
  info        Get information about the server.
  add-mof     Compile MOF and add/update the resulting CIM objects in the...
  remove-mof  Compile MOF and remove the resulting CIM objects from the...

```

**My  suggestions but just a first attempt:**

add-mof change to:

    Compile MOF and add/update CIM objects on the server.

remove-mof;

    Compile MOF and remove CIM objects from the server.

**Comment by andy-maier** [comment]
This error does not show up in the GitHub actions test workflow for PR #888, neither before it was merged nor after it was merged. I verified that also locally, before it was merged and again now on master after it was merged.

I suppose you did something wrong when merging. Does the error show up for you when testing the current master (that has this PR merged)?

**Comment by KSchopmeyer** [comment]
1. the error show up both in the pr and when I run in the latest master.  git pull shows that my master is up-to-date.
2. When error occurs running either with master or our branch (same result) and python 3.6.8 and LInux  Ubuntu 18.04
3. This is running make test or test of just test_server.py
4. Just did a rebase master and it said I am up-to-date

NOTE: The error with the short descriptions may because of formatting in click but we should try to keep the short descriptions short enough that they do not cause the ... line termination in an 80 col terminal.  The add-mof and remove-mof were too long.

The other error I really cannot explain.

**Comment by andy-maier** [comment]
I have created PR #897 which adds Python 3.6 with minimum and latest package levels on Ubuntu to the tests, and otherwise is based on master, i.e. it includes the PR #888.

**Comment by KSchopmeyer** [comment]
Back from vacine.  5 more weeks and I will be fully covered (wait 4 for next shot and week after for it to take effect).

Created a new virtualenv and it works.  However, the part of the issue about the length of the short help on add-mof and remove-mof is still valid. We do not want them to appear as more than one line or as a line that ends in ... because click clips it off and today it is clipping those short help lines.

Compared the pip lists and there were several differences but the one that finally got me was that I my fault.  I did a pip remove pywbem and pip install pywbem that took me back to pywbem 1.1.3. But the failure occured before that also so not really certain. Looks like I should just clean up that one virtual env or trash it and start a new one in any case.

I have to go get a new battery for car so will be out a while.
\

**Comment by andy-maier** [comment]
This went away after the help text was shortened.
