### ISSUE TITLE
Change all tests to use pytest

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#91]
Update the existing tests to use pytest, the standard pywbemcli call in tests/unit/utils.py as of pr #90 and where possible the new pywbem simple_test_function decorator.

These tests all used a hack to create multiple tests in unittest.

**Comment by KSchopmeyer** [comment]
The following pywbemcli tests do not use pytest today:

test_tableformat.py
test_connection_repository.py
test_context_obj.py
test_pywbem_server.py
test_connection.py
test_helpmsgs.py
test_pywbemclicmds.py
test_common.py

As soon as we get

**Comment by andy-maier** [comment]
As of 0.5.0, only the following testcases use unittest (i.e. do not use pytest completely):
```
tests/unit/test_common.py
tests/unit/test_context_obj.py
tests/unit/test_pywbem_server.py
tests/unit/test_tableformat.py
tests/manual/test_pegasus.py
```

**Comment by KSchopmeyer** [comment]
As of pywbemtools 0.7.0 only the following tests use unittest:

test_tableformat.py
26:import unittest
44:class BaseTableTests(unittest.TestCase):
513:    unittest.main()

test_context_obj.py
25:import unittest
31:class ContextObjTests(unittest.TestCase):
69:    unittest.main()

test_common.py
26:import unittest
1470:class SorterTest(unittest.TestCase):
1704:class CreateCIMInstanceTest(unittest.TestCase):

**Comment by andy-maier** [comment]
I grabbed this one.

**Comment by andy-maier** [comment]
PR #734 converts the test for `_common.sort_cimobjects()` to pytest.

**Comment by andy-maier** [comment]
PR #764 addresses this for test_comon.py.

Remaining unittest classes:
* tests/unit/test_context_obj.py:class ContextObjTests(unittest.TestCase):
* tests/unit/test_tableformat.py:class BaseTableTests(unittest.TestCase):

**Comment by andy-maier** [comment]
PR #765 addresses this for test_tableformat.py.

Remaining unittest classes:
* tests/unit/test_context_obj.py:class ContextObjTests(unittest.TestCase):

**Comment by andy-maier** [comment]
PR #772 addresses this for the remaining two test modules (test_context_obj.py and manual/test_pegasus.py).
