### ISSUE TITLE
Refactor pywbemcli and contextobj classes

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#912]
Refactor these classes to:
Part 1

1. Eliminate the use of some of the properties in ContextObj such as conn and wbemserver since they are already used in PywbemServer. Specifically this means putting wbem_server and conn in PywbemServer and removing them from ContextObj. Note that this means changing all references to these two attributes which will cause changes to almost all command action methods (i.e. those that use conn or wbemserver) as art of the server connection

2.PywbemServer objects have a connect/disconnect functionality (although the methods are named create_connection() and reset()), which we could use to properly set up and tear down connections. They way we use this functionality currently is not very straight forward, for example "connection select" creates a new context object and globally patches that in, or commands in interactive mode make a deep copy of PywbemServer and modify it, but do not disconnect properly.

Part2

Refactor the pywbemcli code that rebuilds the PywbemServer object in interactive mode. (This will be a separate pr)

**Comment by andy-maier** [comment]
Note that as of PR #900, the methods in PywbemServer have been renamed to connect() and disconnect().

**Comment by KSchopmeyer** [comment]
To insure that when connections are disconnected we must close any connection when switching to another connection.

Thus, when a new connection is selected, any existing connected connection must be disconnected.

However, I do not know what to do about the issue Andy raised about the messy mechanism for select where we set the new connection into tthe top level context.  That is done specifically because the concept of select makes the selected connection permanent within the interactive session whereas a command like `-n blah class get` only makes the defined connection the target for the single command defined and reverts to the original connection after that command.  In that case we do not have to disconnect the connection being temporarily replaced.

To be honest the whole premise of modifying connection parameters between commands is probably shaky.  Some of them would require a reconnection and others might now.  things like verbose,warn,  log, output-format are not tied to the connection and so can be freely changed on a one time basis in the interactive mode.  However, options like --user --password, --server, that are tied to the PywbemServer actually would require that the connection be reconnected so we would have to treat these like a new but temporary PywbemServer.

COMMENT: I am thinking about this last issue.
