### ISSUE TITLE
Should we allow changing connection file general option in interactive mode

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#920]
Currently we do not allow modifying the definition of the connection file in interactive mode. It seemed to cause extra confusion. **DISCUSSION:**  Should this be modified to allow selecting an alternate connections file or changing to the defaultconnections file in interactive mode.  Ex.

```
 >: pywbemcli -n mock1
pywbemcli: --connections-file localconnections.yaml -n blah class get CIM_ManagedElement
pywbemcli: connection show
    ... would show the original mock1 connection
```

I blocked it because it was just one more complexity when we were originally setting up the use of general options in interactive mode.

I have not yet thought this through completely but so far do not see any real issues other than the fact that there could be persistent server names with the same name in the two files and we do not show that level of detail in any of the reports Connection list, connection show.

**Comment by andy-maier** [comment]
If the behavior is such that it only affects the current command and then falls back to the previous connection file, I would consider that a straight forward behavior.

**Comment by andy-maier** [comment]
I'm not sure I can follow your examples. The scope of using another connections file is always the command that uses it, i.e.

```
$ pywbemcli -C conn1.yml
pywbemcli> connection list  # lists connections from conn1.yml
pywbemcli> -C conn2.yml connection list  # lists connections from conn2.yml
pywbemcli> connection list  # lists connections from conn1.yml again
```

The switching I think can be achieved through the Click context. Each interactive command has its own context, and the context of the outer (command mode) command stays. So if the path name of the connections file specified with -C is stored in the context, it switches automatically as it should. The connections repo which encapsulates the connections file content is already part of the context.

**Comment by KSchopmeyer** [comment]
We agreed to keep the restriction in until we have a compelling reason to remove it.
