### ISSUE TITLE
.bak files created during test

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#923]
`make test` (as of PR #921) creates these two .bak files without cleaning them up:
```
tests/unit/tst_general_options.yaml.bak
tmpconfig.yaml.bak
```

**Comment by andy-maier** [comment]
Initial analysis:
* `tests/unit/tst_general_options.yaml.bak`: This file is a left-over from running testcase "Verify new config file with defined data is created and saved" and the 4 following testcases in test_general_options.py which all specify a connections file via `-C tst_general_options.yaml`. The use of the `-C` option in this testcase has been added in PR #921.
* `tmpconfig.yaml.bak`: This file is a left-over from running testcase "Verify interactive create mock with bad file name does not fail" in test_general_options.py which specifies a connections file via `-C tmpconfig.yaml`. The use of the `-C` option in this testcase has been added in PR #915.

So both have the same reason, the use of `-C` in the testcase. Need to double check how the test command execution deals with connections files, we either will have to improve that to handle connections files specified with `-C`, or we will have to remove `-C` from the testcases because the default file is handled correctly already (i.e. saved and restored).

**Comment by andy-maier** [comment]
The clean way to solve the .bak problem is to make sure connection files do not exist before each testcase, and to clean them up after each testcase.

Howeber, it turns out that the 5 testcases added in PR #921 depend on each other, for example the last one deletes a connection created by the first one:

```
    ['Verify new config file with defined data is created and saved.',
     {'general': ['-v', '-C', CONN_REPO_FP_STR],
      'stdin': ['connection save blah',
                'connection show']},
     {'stdout': ['default-namespace root/cimv2'],
      'test': 'innows'},
     MOCK_SERVER_MODEL, OK],

    ['Verify simple pywbem command against file works.',
     {'general': ['-n', 'blah', '-v', '-C', CONN_REPO_FP_STR],
      'args': ['brand'],
      'cmdgrp': 'server', },
     {'stdout': ['OpenPegasus'],
      'test': 'innows'},
     None, OK],

    ['Verify simple pywbem command with stdin on same connection name.',
     {'general': ['-n', 'blah', '-v', '-C', CONN_REPO_FP_STR],
      'stdin': ['server brand']},
     {'stdout': ['OpenPegasus'],
      'test': 'innows'},
     None, OK],

    ['Verify cmd with -n option in stdin.',
     {'general': ['-n', 'blah', '-v', '-C', CONN_REPO_FP_STR],
      'stdin': ['-n blah -v server brand']},
     {'stdout': ['OpenPegasus'],
      'test': 'innows'},
     None, OK],

    ['Verify interactive create mock with bad file name does not fail.',
     {'general': ['-v', '-C', CONN_REPO_FP_STR],
      'stdin': ['connection delete blah']},
     {'stdout': ['Deleted connection "blah"'],
      'test': 'innows', },
     None, OK],
 ```

**DISCUSSION:** I suggest that we establish the rule that each testcase must not depend on other testcases.

**Comment by KSchopmeyer** [comment]
I disagree with this one.  We really cannot do out tests if each test case is completely independent since some tests depend particular environments being setup.  Thus the example above runs multiple commands and you cannot confirm that they are really correct in a single test.  By the way, both the default and the specified connections files create a backup each time the file is changed.   I specifically chose NOT to remove the backup if the last connection is removed from the connections file and the connections file deleted since the backup is alway the state of the connections file before the last change and that is the connection that is removed.

**Comment by andy-maier** [comment]
There are multiple ways how connection files can be built for a single testcase:
* The testcase itself builds it
* We define testcase input for setting up an initial connection file
* We extend the testcase definition so that one testcase defines multiple pywbemcli invocations.
A fixture for that is not easy to combine with the simplified testcase concept.

In any case, having testcases depend on each other is very bad.

**Comment by andy-maier** [comment]
We ended up with agreeing that testcases should not depend on each other.

**Comment by andy-maier** [comment]
The key to addressing this was the introduction of a context manager "connections_file" that creates and cleans up connections files, in PR #942 .
