### ISSUE TITLE
Add support for case independence when using toposort. 

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#954]
the python package toposort is used to sort classes for at least the namespace delete function to dependency sort classes.  However toposort is not a case-independent function and CIM classnames are. We need to extend this capability to allow case-independent toposort.

Moved from a TODO to this issue  as of the release of pywbemtools 0.9.0

**Comment by andy-maier** [comment]
We agreed in the call today to close this one: Not important enough.
