### ISSUE TITLE
Bring make system up to date with changes in other environments

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#96]
There have been a number of changes in the build environments of the other tools that use our concept of makefile, requirements.txt, etc. since pywbemtools make tools were last update in November 2017.

We need to resync.

For example:

python-coveralls 2.9.1 has requirement coverage==4.0.3, but you'll have coverage 4.4.1 which is incompatible.

**Comment by andy-maier** [comment]
PR #100 already did some of that.

**Comment by KSchopmeyer** [comment]
This was done in PRs # 167, 168,170, 171. The two make environments are now close to gether in install/setup files, and the contents of those files.

Closing as complete
