### ISSUE TITLE
Add 'listener send' command

### ISSUE THREAD

**Issue by andy-maier** [pywbem/pywbemtools#966]
Add support for a 'send' command in the 'listener' command group, which would send an indication to a listener.

The targeted listener may be a pywbemcli listener on the same system, or on a different system, or a different type of listener.

The indication can be specified in the command line.

**Comment by KSchopmeyer** [comment]
Note: I have put a command into pywbemcli subscription that  creates a subscription in the server and tells the server to send some indications.  However, I think that is different than your 'send'.

**Comment by andy-maier** [comment]
Yes, that is different. This send here would not depend on a server implementing a provider that can be triggered to perform a send, but instead would perform the send directly. Also, the target listener would be specified by its name, so it would be useable only for pywbemlistener based listeners.

**Comment by andy-maier** [comment]
It turns out this depends on a not yet existing functionality in pywbem to send an indication to a listener. I suggest to add that to `pywbem.WBEMConnection` and have opened issue TBD for that.
