### ISSUE TITLE
Bring cmd line processing for instance paths in line with url changes

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#97]
Bring our cmd line processing of urls into line with the wbem_url defined in pywbem 0.12.0

**Comment by andy-maier** [comment]
As of 0.5.0, INSTANCENAME is defined properly ([docs](https://pywbemtools.readthedocs.io/en/latest/pywbemclifeatures.html#specifying-the-instancename-command-argument)), and there are intentional simplifications relative to WBEM URI.
I suggest to close this issue.

**Comment by KSchopmeyer** [comment]
Agreed and closed
