### ISSUE TITLE
As of 7 May, Travis no longer runs on commit

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#99]
As of this weekend the travis for pywbemcli does not run on the server. It was running late last week and even over most of the weekend.  In fact, it may be just today that it stopped

**Comment by andy-maier** [comment]
The pywbemtools project was not active in Travis: 
![image](https://user-images.githubusercontent.com/8939758/39753103-e60af588-52bd-11e8-95fc-aede89a66a4f.png)

I activated it. Let's see if that helps.

**Comment by andy-maier** [comment]
I verified that activation of the project in Travis solved the issue, using the manual-ci-run branch.

What remains to be done is that for each open PR that does not yet have a Travis run, to trigger the run by pushing up a change.

**Comment by KSchopmeyer** [comment]
Thanks
